#debug
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import mods.ItemStages;

function stageItems(stage as string, items as IItemStack[]) {
  for item in items {
    ItemStages.addItemStage(stage,item);
  }
}



stageItems("Nuclear Tech 2",[
    <nuclearcraft:solid_fission_sink>,
    <nuclearcraft:solid_fission_sink:1>,
    <nuclearcraft:solid_fission_sink:2>,
    <nuclearcraft:solid_fission_sink:3>,
    <nuclearcraft:solid_fission_sink:4>,
    <nuclearcraft:solid_fission_sink:5>,
    <nuclearcraft:solid_fission_sink:6>,
    <nuclearcraft:solid_fission_sink:7>,
    <nuclearcraft:solid_fission_sink:8>,
    <nuclearcraft:solid_fission_sink:9>,
    <nuclearcraft:solid_fission_sink:10>,
    <nuclearcraft:solid_fission_sink:11>,
    <nuclearcraft:solid_fission_sink:12>,
    <nuclearcraft:solid_fission_sink:13>,
    <nuclearcraft:solid_fission_sink:14>,
    <nuclearcraft:solid_fission_sink:15>,
    <nuclearcraft:solid_fission_sink2>,
    <nuclearcraft:solid_fission_sink2:1>,
    <nuclearcraft:solid_fission_sink2:2>,
    <nuclearcraft:solid_fission_sink2:3>,
    <nuclearcraft:solid_fission_sink2:4>,
    <nuclearcraft:solid_fission_sink2:5>,
    <nuclearcraft:solid_fission_sink2:6>,
    <nuclearcraft:solid_fission_sink2:7>,
    <nuclearcraft:solid_fission_sink2:8>,
    <nuclearcraft:solid_fission_sink2:9>,
    <nuclearcraft:solid_fission_sink2:10>,
    <nuclearcraft:solid_fission_sink2:11>,
    <nuclearcraft:solid_fission_sink2:12>,
    <nuclearcraft:solid_fission_sink2:13>,
    <nuclearcraft:solid_fission_sink2:14>,
    <nuclearcraft:solid_fission_sink2:15>,
    <nuclearcraft:part:14>,
    <nuclearcraft:salt_fission_heater2:15>,
    <nuclearcraft:salt_fission_heater2:14>,
    <nuclearcraft:salt_fission_heater2:13>,
    <nuclearcraft:salt_fission_heater2:12>,
    <nuclearcraft:salt_fission_heater2:11>,
    <nuclearcraft:salt_fission_heater2:10>,
    <nuclearcraft:salt_fission_heater2:9>,
    <nuclearcraft:salt_fission_heater2:8>,
    <nuclearcraft:salt_fission_heater2:7>,
    <nuclearcraft:salt_fission_heater2:6>,
    <nuclearcraft:salt_fission_heater2:5>,
    <nuclearcraft:salt_fission_heater2:4>,
    <nuclearcraft:salt_fission_heater2:3>,
    <nuclearcraft:salt_fission_heater2:2>,
    <nuclearcraft:salt_fission_heater2:1>,
    <nuclearcraft:salt_fission_heater2>,
    <nuclearcraft:salt_fission_heater:15>,
    <nuclearcraft:salt_fission_heater:14>,
    <nuclearcraft:salt_fission_heater:13>,
    <nuclearcraft:salt_fission_heater:12>,
    <nuclearcraft:salt_fission_heater:11>,
    <nuclearcraft:salt_fission_heater:10>,
    <nuclearcraft:salt_fission_heater:9>,
    <nuclearcraft:salt_fission_heater:8>,
    <nuclearcraft:salt_fission_heater:7>,
    <nuclearcraft:salt_fission_heater:6>,
    <nuclearcraft:salt_fission_heater:5>,
    <nuclearcraft:salt_fission_heater:4>,
    <nuclearcraft:salt_fission_heater:3>,
    <nuclearcraft:salt_fission_heater:2>,
    <nuclearcraft:salt_fission_heater:1>,
    <nuclearcraft:salt_fission_heater>,
    <nuclearcraft:fission_heater_port2:15>,
    <nuclearcraft:fission_heater_port2:14>,
    <nuclearcraft:fission_heater_port2:13>,
    <nuclearcraft:fission_heater_port2:12>,
    <nuclearcraft:fission_heater_port2:11>,
    <nuclearcraft:fission_heater_port2:10>,
    <nuclearcraft:fission_heater_port2:9>,
    <nuclearcraft:fission_heater_port2:8>,
    <nuclearcraft:fission_heater_port2:7>,
    <nuclearcraft:fission_heater_port2:6>,
    <nuclearcraft:fission_heater_port2:5>,
    <nuclearcraft:fission_heater_port2:4>,
    <nuclearcraft:fission_heater_port2:3>,
    <nuclearcraft:fission_heater_port2:2>,
    <nuclearcraft:fission_heater_port2:1>,
    <nuclearcraft:fission_heater_port2>,
    <nuclearcraft:fission_heater_port:15>,
    <nuclearcraft:fission_heater_port:14>,
    <nuclearcraft:fission_heater_port:13>,
    <nuclearcraft:fission_heater_port:12>,
    <nuclearcraft:fission_heater_port:11>,
    <nuclearcraft:fission_heater_port:10>,
    <nuclearcraft:fission_heater_port:9>,
    <nuclearcraft:fission_heater_port:8>,
    <nuclearcraft:fission_heater_port:7>,
    <nuclearcraft:fission_heater_port:6>,
    <nuclearcraft:fission_heater_port:5>,
    <nuclearcraft:fission_heater_port:4>,
    <nuclearcraft:fission_heater_port:3>,
    <nuclearcraft:fission_heater_port:2>,
    <nuclearcraft:fission_heater_port:1>,
    <nuclearcraft:fission_heater_port>,
    <nuclearcraft:depleted_fuel_californium:15>,
    <nuclearcraft:depleted_fuel_californium:14>,
    <nuclearcraft:depleted_fuel_californium:13>,
    <nuclearcraft:depleted_fuel_californium:12>,
    <nuclearcraft:depleted_fuel_californium:11>,
    <nuclearcraft:depleted_fuel_californium:10>,
    <nuclearcraft:depleted_fuel_californium:9>,
    <nuclearcraft:depleted_fuel_californium:8>,
    <nuclearcraft:depleted_fuel_californium:7>,
    <nuclearcraft:depleted_fuel_californium:6>,
    <nuclearcraft:depleted_fuel_californium:5>,
    <nuclearcraft:depleted_fuel_californium:4>,
    <nuclearcraft:depleted_fuel_californium:3>,
    <nuclearcraft:depleted_fuel_californium:2>,
    <nuclearcraft:depleted_fuel_californium:1>,
    <nuclearcraft:depleted_fuel_californium>,
    <nuclearcraft:depleted_fuel_berkelium:7>,
    <nuclearcraft:depleted_fuel_berkelium:6>,
    <nuclearcraft:depleted_fuel_berkelium:5>,
    <nuclearcraft:depleted_fuel_berkelium:4>,
    <nuclearcraft:depleted_fuel_berkelium:3>,
    <nuclearcraft:depleted_fuel_berkelium:2>,
    <nuclearcraft:depleted_fuel_berkelium:1>,
    <nuclearcraft:depleted_fuel_berkelium>,
    <nuclearcraft:depleted_fuel_curium:23>,
    <nuclearcraft:depleted_fuel_curium:22>,
    <nuclearcraft:depleted_fuel_curium:21>,
    <nuclearcraft:depleted_fuel_curium:20>,
    <nuclearcraft:depleted_fuel_curium:19>,
    <nuclearcraft:depleted_fuel_curium:18>,
    <nuclearcraft:depleted_fuel_curium:17>,
    <nuclearcraft:depleted_fuel_curium:16>,
    <nuclearcraft:depleted_fuel_curium:15>,
    <nuclearcraft:depleted_fuel_curium:14>,
    <nuclearcraft:depleted_fuel_curium:13>,
    <nuclearcraft:depleted_fuel_curium:12>,
    <nuclearcraft:depleted_fuel_curium:11>,
    <nuclearcraft:depleted_fuel_curium:10>,
    <nuclearcraft:depleted_fuel_curium:9>,
    <nuclearcraft:depleted_fuel_curium:8>,
    <nuclearcraft:depleted_fuel_curium:7>,
    <nuclearcraft:depleted_fuel_curium:6>,
    <nuclearcraft:depleted_fuel_curium:5>,
    <nuclearcraft:depleted_fuel_curium:4>,
    <nuclearcraft:depleted_fuel_curium:3>,
    <nuclearcraft:depleted_fuel_curium:2>,
    <nuclearcraft:depleted_fuel_curium:1>,
    <nuclearcraft:depleted_fuel_curium>,
    <nuclearcraft:depleted_fuel_americium:7>,
    <nuclearcraft:depleted_fuel_americium:6>,
    <nuclearcraft:depleted_fuel_americium:5>,
    <nuclearcraft:depleted_fuel_americium:4>,
    <nuclearcraft:depleted_fuel_americium:3>,
    <nuclearcraft:depleted_fuel_americium:2>,
    <nuclearcraft:depleted_fuel_americium:1>,
    <nuclearcraft:depleted_fuel_americium>,
    <nuclearcraft:depleted_fuel_mixed:7>,
    <nuclearcraft:depleted_fuel_mixed:6>,
    <nuclearcraft:depleted_fuel_mixed:5>,
    <nuclearcraft:depleted_fuel_mixed:4>,
    <nuclearcraft:depleted_fuel_mixed:3>,
    <nuclearcraft:depleted_fuel_mixed:2>,
    <nuclearcraft:depleted_fuel_mixed:1>,
    <nuclearcraft:depleted_fuel_mixed>,
    <nuclearcraft:depleted_fuel_plutonium:15>,
    <nuclearcraft:depleted_fuel_plutonium:14>,
    <nuclearcraft:depleted_fuel_plutonium:13>,
    <nuclearcraft:depleted_fuel_plutonium:12>,
    <nuclearcraft:depleted_fuel_plutonium:11>,
    <nuclearcraft:depleted_fuel_plutonium:10>,
    <nuclearcraft:depleted_fuel_plutonium:9>,
    <nuclearcraft:depleted_fuel_plutonium:8>,
    <nuclearcraft:depleted_fuel_plutonium:7>,
    <nuclearcraft:depleted_fuel_plutonium:6>,
    <nuclearcraft:depleted_fuel_plutonium:5>,
    <nuclearcraft:depleted_fuel_plutonium:4>,
    <nuclearcraft:depleted_fuel_plutonium:3>,
    <nuclearcraft:depleted_fuel_plutonium:2>,
    <nuclearcraft:depleted_fuel_plutonium:1>,
    <nuclearcraft:depleted_fuel_plutonium>,
    <nuclearcraft:depleted_fuel_neptunium:7>,
    <nuclearcraft:depleted_fuel_neptunium:6>,
    <nuclearcraft:depleted_fuel_neptunium:5>,
    <nuclearcraft:depleted_fuel_neptunium:4>,
    <nuclearcraft:depleted_fuel_neptunium:3>,
    <nuclearcraft:depleted_fuel_neptunium:2>,
    <nuclearcraft:depleted_fuel_neptunium:1>,
    <nuclearcraft:depleted_fuel_neptunium>,
    <nuclearcraft:depleted_fuel_uranium:15>,
    <nuclearcraft:depleted_fuel_uranium:14>,
    <nuclearcraft:depleted_fuel_uranium:13>,
    <nuclearcraft:depleted_fuel_uranium:12>,
    <nuclearcraft:depleted_fuel_uranium:11>,
    <nuclearcraft:depleted_fuel_uranium:10>,
    <nuclearcraft:depleted_fuel_uranium:9>,
    <nuclearcraft:depleted_fuel_uranium:8>,
    <nuclearcraft:depleted_fuel_uranium:7>,
    <nuclearcraft:depleted_fuel_uranium:6>,
    <nuclearcraft:depleted_fuel_uranium:5>,
    <nuclearcraft:depleted_fuel_uranium:4>,
    <nuclearcraft:depleted_fuel_uranium:3>,
    <nuclearcraft:depleted_fuel_uranium:2>,
    <nuclearcraft:depleted_fuel_uranium:1>,
    <nuclearcraft:depleted_fuel_uranium>,
    <nuclearcraft:depleted_fuel_thorium:3>,
    <nuclearcraft:depleted_fuel_thorium:2>,
    <nuclearcraft:depleted_fuel_thorium:1>,
    <nuclearcraft:depleted_fuel_thorium>,
    <nuclearcraft:fuel_californium:15>,
    <nuclearcraft:fuel_californium:14>,
    <nuclearcraft:fuel_californium:13>,
    <nuclearcraft:fuel_californium:12>,
    <nuclearcraft:fuel_californium:11>,
    <nuclearcraft:fuel_californium:10>,
    <nuclearcraft:fuel_californium:9>,
    <nuclearcraft:fuel_californium:8>,
    <nuclearcraft:fuel_californium:7>,
    <nuclearcraft:fuel_californium:6>,
    <nuclearcraft:fuel_californium:5>,
    <nuclearcraft:fuel_californium:4>,
    <nuclearcraft:fuel_californium:3>,
    <nuclearcraft:fuel_californium:2>,
    <nuclearcraft:fuel_californium:1>,
    <nuclearcraft:fuel_californium>,
    <nuclearcraft:fuel_berkelium:7>,
    <nuclearcraft:fuel_berkelium:6>,
    <nuclearcraft:fuel_berkelium:5>,
    <nuclearcraft:fuel_berkelium:4>,
    <nuclearcraft:fuel_berkelium:3>,
    <nuclearcraft:fuel_berkelium:2>,
    <nuclearcraft:fuel_berkelium:1>,
    <nuclearcraft:fuel_berkelium>,
    <nuclearcraft:fuel_curium:23>,
    <nuclearcraft:fuel_curium:22>,
    <nuclearcraft:fuel_curium:21>,
    <nuclearcraft:fuel_curium:20>,
    <nuclearcraft:fuel_curium:19>,
    <nuclearcraft:fuel_curium:18>,
    <nuclearcraft:fuel_curium:17>,
    <nuclearcraft:fuel_curium:16>,
    <nuclearcraft:fuel_curium:15>,
    <nuclearcraft:fuel_curium:14>,
    <nuclearcraft:fuel_americium:5>,
    <nuclearcraft:fuel_americium:6>,
    <nuclearcraft:fuel_americium:7>,
    <nuclearcraft:fuel_curium>,
    <nuclearcraft:fuel_curium:1>,
    <nuclearcraft:fuel_curium:2>,
    <nuclearcraft:fuel_curium:3>,
    <nuclearcraft:fuel_curium:4>,
    <nuclearcraft:fuel_curium:5>,
    <nuclearcraft:fuel_curium:6>,
    <nuclearcraft:fuel_curium:7>,
    <nuclearcraft:fuel_curium:8>,
    <nuclearcraft:fuel_curium:9>,
    <nuclearcraft:fuel_curium:10>,
    <nuclearcraft:fuel_curium:11>,
    <nuclearcraft:fuel_curium:12>,
    <nuclearcraft:fuel_curium:13>,
    <nuclearcraft:fuel_americium:4>,
    <nuclearcraft:fuel_americium:3>,
    <nuclearcraft:fuel_americium:2>,
    <nuclearcraft:fuel_americium:1>,
    <nuclearcraft:fuel_americium>,
    <nuclearcraft:fuel_mixed:7>,
    <nuclearcraft:fuel_mixed:6>,
    <nuclearcraft:fuel_mixed:5>,
    <nuclearcraft:fuel_mixed:4>,
    <nuclearcraft:fuel_mixed:3>,
    <nuclearcraft:fuel_mixed:2>,
    <nuclearcraft:fuel_mixed:1>,
    <nuclearcraft:fuel_mixed>,
    <nuclearcraft:fuel_plutonium:15>,
    <nuclearcraft:fuel_plutonium:14>,
    <nuclearcraft:fuel_plutonium:13>,
    <nuclearcraft:fuel_plutonium:12>,
    <nuclearcraft:fuel_neptunium:3>,
    <nuclearcraft:fuel_neptunium:4>,
    <nuclearcraft:fuel_neptunium:5>,
    <nuclearcraft:fuel_neptunium:6>,
    <nuclearcraft:fuel_neptunium:7>,
    <nuclearcraft:fuel_plutonium>,
    <nuclearcraft:fuel_plutonium:1>,
    <nuclearcraft:fuel_plutonium:2>,
    <nuclearcraft:fuel_plutonium:3>,
    <nuclearcraft:fuel_plutonium:4>,
    <nuclearcraft:fuel_plutonium:5>,
    <nuclearcraft:fuel_plutonium:6>,
    <nuclearcraft:fuel_plutonium:7>,
    <nuclearcraft:fuel_plutonium:8>,
    <nuclearcraft:fuel_plutonium:9>,
    <nuclearcraft:fuel_plutonium:10>,
    <nuclearcraft:fuel_plutonium:11>,
    <nuclearcraft:fuel_neptunium:2>,
    <nuclearcraft:fuel_neptunium:1>,
    <nuclearcraft:fuel_neptunium>,
    <nuclearcraft:fuel_uranium:15>,
    <nuclearcraft:fuel_uranium:14>,
    <nuclearcraft:fuel_uranium:13>,
    <nuclearcraft:fuel_uranium:12>,
    <nuclearcraft:fuel_uranium:11>,
    <nuclearcraft:fuel_uranium:10>,
    <nuclearcraft:fuel_uranium:9>,
    <nuclearcraft:fuel_uranium:8>,
    <nuclearcraft:fuel_uranium:7>,
    <nuclearcraft:fuel_uranium:6>,
    <nuclearcraft:fuel_uranium:5>,
    <nuclearcraft:fuel_uranium:4>,
    <nuclearcraft:fuel_uranium:3>,
    <nuclearcraft:fuel_uranium:2>,
    <nuclearcraft:fuel_uranium:1>,
    <nuclearcraft:fuel_uranium>,
    <nuclearcraft:fuel_thorium:3>,
    <nuclearcraft:fuel_thorium:2>,
    <nuclearcraft:fuel_thorium:1>,
    <nuclearcraft:fuel_thorium>,
    <nuclearcraft:fission_casing>,
    <nuclearcraft:fission_glass>,
    <nuclearcraft:fission_conductor>,
    <nuclearcraft:fission_monitor>,
    <nuclearcraft:fission_power_port>,
    <nuclearcraft:fission_vent>,
    <reactorbuilder:reactorbuilder>,
    <nuclearcraft:fission_irradiator_port>,
    <nuclearcraft:fission_cell_port>,
    <nuclearcraft:fission_vessel_port>,
    <nuclearcraft:fission_irradiator>,
    <ncsteamadditions:dust:1>
]);

stageItems("Quantum Tech",[
    <qmd:part:3>,
    <qmd:part:2>,
    <qmd:semiconductor:3>,
    <qmd:semiconductor:1>,
    <qmd:semiconductor>,
    <qmd:ingot2>,
    <qmd:ingot2:1>,
    <qmd:semiconductor:6>,
    <qmd:beamline>,
    <qmd:linear_accelerator_controller>,
    <qmd:ring_accelerator_controller>,
    <qmd:accelerator_beam>,
    <qmd:accelerator_casing>,
    <qmd:accelerator_computer_port>,
    <qmd:accelerator_redstone_port>,
    <qmd:accelerator_port>,
    <qmd:accelerator_glass>,
    <qmd:accelerator_vent>,
    <qmd:accelerator_beam_port>,
    <qmd:accelerator_synchrotron_port>,
    <qmd:accelerator_cavity>,
    <qmd:accelerator_cavity:1>,
    <qmd:accelerator_cavity:2>,
    <qmd:accelerator_cavity:3>,
    <qmd:accelerator_cavity:4>,
    <qmd:accelerator_magnet>,
    <qmd:accelerator_magnet:1>,
    <qmd:accelerator_magnet:2>,
    <qmd:accelerator_magnet:3>,
    <qmd:accelerator_magnet:4>,
    <qmd:accelerator_yoke>,
    <qmd:accelerator_cooler1>,
    <qmd:accelerator_cooler1:1>,
    <qmd:accelerator_cooler1:2>,
    <qmd:accelerator_cooler1:3>,
    <qmd:accelerator_cooler1:4>,
    <qmd:accelerator_cooler1:5>,
    <qmd:accelerator_cooler1:6>,
    <qmd:accelerator_cooler1:7>,
    <qmd:accelerator_cooler1:8>,
    <qmd:accelerator_cooler1:9>,
    <qmd:accelerator_cooler1:10>,
    <qmd:accelerator_cooler1:11>,
    <qmd:accelerator_cooler1:12>,
    <qmd:accelerator_cooler1:13>,
    <qmd:accelerator_cooler1:14>,
    <qmd:accelerator_cooler1:15>,
    <qmd:accelerator_cooler2>,
    <qmd:accelerator_cooler2:1>,
    <qmd:accelerator_cooler2:2>,
    <qmd:accelerator_cooler2:3>,
    <qmd:accelerator_cooler2:4>,
    <qmd:accelerator_cooler2:5>,
    <qmd:accelerator_cooler2:6>,
    <qmd:accelerator_cooler2:7>,
    <qmd:accelerator_cooler2:8>,
    <qmd:accelerator_cooler2:9>,
    <qmd:accelerator_cooler2:10>,
    <qmd:accelerator_cooler2:11>,
    <qmd:accelerator_cooler2:12>,
    <qmd:accelerator_cooler2:13>,
    <qmd:accelerator_cooler2:14>,
    <qmd:accelerator_cooler2:15>,
    <qmd:accelerator_source>,
    <qmd:accelerator_energy_port>,
    <qmd:beam_diverter_controller>,
    <qmd:beam_splitter_controller>,
    <qmd:decelerator_controller>,
    <qmd:target_chamber_controller>,
    <qmd:decay_chamber_controller>,
    <qmd:beam_dump_controller>,
    <qmd:collision_chamber_controller>,
    <qmd:particle_chamber_beam>,
    <qmd:particle_chamber_casing>,
    <qmd:particle_chamber_glass>,
    <qmd:particle_chamber_beam_port>,
    <qmd:particle_chamber_detector>,
    <qmd:particle_chamber_detector:1>,
    <qmd:particle_chamber_detector:2>,
    <qmd:particle_chamber_detector:3>,
    <qmd:particle_chamber_detector:4>,
    <qmd:particle_chamber_energy_port>,
    <qmd:particle_chamber>,
    <qmd:particle_chamber_port>,
    <qmd:particle_chamber_fluid_port>,
    <qmd:neutral_containment_controller>,
    <qmd:nucleosynthesis_chamber_controller>,
    <qmd:containment_casing>,
    <qmd:containment_glass>,
    <qmd:containment_port>,
    <qmd:containment_beam_port>,
    <qmd:containment_vent>,
    <qmd:containment_energy_port>,
    <qmd:vacuum_chamber_fluid_port>,
    <qmd:containment_coil>,
    <qmd:containment_laser>,
    <qmd:vacuum_chamber_beam>,
    <qmd:vacuum_chamber_plasma_glass>,
    <qmd:vacuum_chamber_plasma_nozzle>,
    <qmd:vacuum_chamber_heater>,
    <qmd:vacuum_chamber_heater:1>,
    <qmd:vacuum_chamber_heater:2>,
    <qmd:vacuum_chamber_heater:3>,
    <qmd:vacuum_chamber_heater:4>,
    <qmd:vacuum_chamber_heater:5>,
    <qmd:vacuum_chamber_heater:6>,
    <qmd:vacuum_chamber_heater:7>,
    <qmd:vacuum_chamber_heater_vent>,
    <qmd:vacuum_chamber_redstone_port>,
    <qmd:strontium_90_block>,
    <qmd:cell>,
    <qmd:cell:1>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:cell:2>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:cell:3>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:cell:4>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:cell:5>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:cell:6>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:cell:7>.withTag({particle_storage: {particle_amount: 10000}}),
    <qmd:cell:8>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:cell:9>.withTag({particle_storage: {particle_amount: 100000}}),
    <qmd:boots_hev>.withTag({energyStorage: {energy: 0 as long, capacity: 1000000 as long}}),
    <qmd:legs_hev>.withTag({energyStorage: {energy: 0 as long, capacity: 1000000 as long}}),
    <qmd:chest_hev>.withTag({energyStorage: {energy: 0 as long, capacity: 1000000 as long}}),
    <qmd:helm_hev>.withTag({energyStorage: {energy: 0 as long, capacity: 1000000 as long}}),
    <qmd:gluon_gun>,
    <qmd:antimatter_launcher>,
    <qmd:lepton_cannon>,
    <qmd:semiconductor:4>,
    <qmd:semiconductor:5>,
    <qmd:canister>,
    <qmd:canister:1>.withTag({particle_storage: {particle_amount: 10000000}}),
    <qmd:canister:2>.withTag({particle_storage: {particle_amount: 10000000}}),
    <qmd:canister:3>.withTag({particle_storage: {particle_amount: 10000000}}),
    <qmd:canister:4>.withTag({particle_storage: {particle_amount: 10000000}}),
    <qmd:canister:5>.withTag({particle_storage: {particle_amount: 10000000}}),
    <qmd:canister:6>.withTag({particle_storage: {particle_amount: 10000000}}),
    <qmd:source>.withTag({particle_storage: {particle_amount: 50000000}}),
    <qmd:source:1>.withTag({particle_storage: {particle_amount: 5000000}}),
    <qmd:source:2>.withTag({particle_storage: {particle_amount: 1000000}}),
    <qmd:source:3>.withTag({particle_storage: {particle_amount: 1000000}}),
    <qmd:source:4>.withTag({particle_storage: {particle_amount: 5000000}}),
    <qmd:part:9>,
    <qmd:part:10>,
    <qmd:part:8>,
    <qmd:part:7>,
    <qmd:part:1>,
    <qmd:part>
]);

stageItems("Nuclear Tech",[
    <industrialupgrade:basemachine1:7>,
    <industrialupgrade:basemachine1:8>,
    <industrialupgrade:basemachine1:9>,
    <industrialupgrade:imp_chamber>,
    <industrialupgrade:adv_chamber>,
    <industrialupgrade:per_chamber>,
    <ic2:te:22>,
    <ic2:te:24>,
    <ic2:te:23>,
    <ic2:te:25>,
    <ic2:te:26>,
    <ic2:te:84>,
    <ic2:te:85>,
    <ic2:resource:14>,
    <ic2:plating>,
    <ic2:heat_plating>,
    <ic2:containment_plating>,
    <ic2:reactor_heat_exchanger>.withTag({advDmg: 0}),
    <ic2:reactor_heat_vent>.withTag({advDmg: 0}),
    <ic2:nuclear:*>,
    <ic2:uranium_fuel_rod>.withTag({advDmg: 0}),
    <ic2:dual_uranium_fuel_rod>.withTag({advDmg: 0}),
    <ic2:quad_uranium_fuel_rod>.withTag({advDmg: 0}),
    <ic2:mox_fuel_rod>.withTag({advDmg: 0}),
    <ic2:dual_mox_fuel_rod>.withTag({advDmg: 0}),
    <ic2:quad_mox_fuel_rod>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedprotonsimple>,
    <industrialupgrade:reactordepletedprotondual>,
    <industrialupgrade:reactordepletedprotonquad>,
    <industrialupgrade:reactordepletedprotoneit>,
    <industrialupgrade:reactorprotonsimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactorprotondual>.withTag({advDmg: 0}),
    <industrialupgrade:reactorprotonquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactorprotoneit>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedtoriysimple>,
    <industrialupgrade:reactordepletedtoriydual>,
    <industrialupgrade:reactordepletedtoriyquad>,
    <industrialupgrade:reactortoriysimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactortoriydual>.withTag({advDmg: 0}),
    <industrialupgrade:reactortoriyquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedamericiumsimple>,
    <industrialupgrade:reactordepletedamericiumdual>,
    <industrialupgrade:reactordepletedamericiumquad>,
    <industrialupgrade:reactoramericiumsimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactoramericiumdual>.withTag({advDmg: 0}),
    <industrialupgrade:reactoramericiumquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedneptuniumsimple>,
    <industrialupgrade:reactordepletedneptuniumdual>,
    <industrialupgrade:reactordepletedneptuniumquad>,
    <industrialupgrade:reactorneptuniumsimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactorneptuniumdual>.withTag({advDmg: 0}),
    <industrialupgrade:reactorneptuniumquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedcuriumsimple>,
    <industrialupgrade:reactordepletedcuriumdual>,
    <industrialupgrade:reactordepletedcuriumquad>,
    <industrialupgrade:reactorcuriumsimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactorcuriumdual>.withTag({advDmg: 0}),
    <industrialupgrade:reactorcuriumquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedcaliforniasimple>,
    <industrialupgrade:reactordepletedcaliforniadual>,
    <industrialupgrade:reactordepletedcaliforniaquad>,
    <industrialupgrade:reactorcaliforniasimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactorcaliforniadual>.withTag({advDmg: 0}),
    <industrialupgrade:reactorcaliforniaquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedmendeleviumsimple>,
    <industrialupgrade:reactordepletedmendeleviumdual>,
    <industrialupgrade:reactordepletedmendeleviumquad>,
    <industrialupgrade:reactormendeleviumsimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactormendeleviumdual>.withTag({advDmg: 0}),
    <industrialupgrade:reactormendeleviumquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedberkeliumsimple>,
    <industrialupgrade:reactordepletedberkeliumdual>,
    <industrialupgrade:reactordepletedberkeliumquad>,
    <industrialupgrade:reactorberkeliumsimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactorberkeliumdual>.withTag({advDmg: 0}),
    <industrialupgrade:reactorberkeliumquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepletedeinsteiniumsimple>,
    <industrialupgrade:reactordepletedeinsteiniumdual>,
    <industrialupgrade:reactordepletedeinsteiniumquad>,
    <industrialupgrade:reactoreinsteiniumsimple>.withTag({advDmg: 0}),
    <industrialupgrade:reactoreinsteiniumdual>.withTag({advDmg: 0}),
    <industrialupgrade:reactoreinsteiniumquad>.withTag({advDmg: 0}),
    <industrialupgrade:reactordepleteduran233simple>,
    <industrialupgrade:reactordepleteduran233dual>,
    <industrialupgrade:reactordepleteduran233quad>,
    <industrialupgrade:reactoruran233simple>.withTag({advDmg: 0}),
    <industrialupgrade:reactoruran233dual>.withTag({advDmg: 0}),
    <industrialupgrade:reactoruran233quad>.withTag({advDmg: 0}),
    <industrialupgrade:radiationresources:*>,
    <chisel:blockuranium:*>,
    <immersiveengineering:storage_slab:5>,
    <immersiveengineering:sheetmetal:5>,
    <immersiveengineering:sheetmetal_slab:5>,
    <immersiveengineering:metal:35>,
    <industrialupgrade:itemiucrafring>,
    <industrialupgrade:itemiucrafring:2>,
    <ic2:purified:6>,
    <ic2:crushed:6>,
    <ic2:resource:10>,
    <nuclearcraft:rtg_uranium>,
    <nuclearcraft:fertile_isotope>
]);

stageItems("Basic Ores",[
    <ic2:ingot:2>,
    <ic2:plate:1>,
    <ic2:plate:10>,
    <ic2:casing:1>,
    <immersiveengineering:sheetmetal>,
    <ic2:crafting:8>,
    <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}),
    <ic2:cable>.withTag({type: 0 as byte, insulation: 1 as byte}),
    <ironchest:copper_silver_chest_upgrade>,
    <ironchest:copper_iron_chest_upgrade>,
    <ironchest:wood_copper_chest_upgrade>,
    <ironchest:copper_silver_shulker_upgrade>,
    <ironchest:copper_iron_shulker_upgrade>,
    <ironchest:vanilla_copper_shulker_upgrade>,
    <ironchest:iron_chest:3>,
    <ic2:dust:4>,
    <ic2:dust:19>,
    <ic2:purified>,
    <ic2:crushed>,
    <ic2:resource:6>,
    <nuclearcraft:part:4>,
    <galacticraftcore:basic_item:6>,
    <immersiveengineering:sheetmetal_slab>,
    <immersiveengineering:metal_decoration0>,
    <immersiveengineering:storage>,
    <immersiveengineering:storage_slab>,
    <chisel:blockcopper>,
    <thermalfoundation:material:256>,
    <galacticraftcore:canister:1>,
    <mekanism:clump:3>,
    <mekanism:dirtydust:3>,
    <mekanism:shard:3>,
    <mekanism:crystal:3>,
    <thermalfoundation:material:259>,
    <ic2:ingot:3>,
    <ic2:dust:23>,
    <ic2:dust:10>,
    <ic2:purified:3>,
    <ic2:crushed:3>,
    <ic2:resource:7>,
    <ic2:plate:5>,
    <ic2:plate:14>,
    <ic2:casing:4>,
    <mekanism:clump:6>,
    <mekanism:dirtydust:6>,
    <mekanism:shard:6>,
    <mekanism:crystal:6>,
    <immersiveengineering:stone_decoration:7>,
    <immersiveengineering:stone_decoration_slab:7>,
    <immersiveengineering:stone_decoration_stairs_concrete_leaded>,
    <immersiveengineering:sheetmetal:2>,
    <immersiveengineering:sheetmetal_slab:2>,
    <immersiveengineering:storage_slab:2>,
    <ic2:ingot:6>,
    <ic2:plate:8>,
    <ic2:plate:17>,
    <ic2:casing:6>,
    <ic2:dust:17>,
    <ic2:purified:5>,
    <ic2:crushed:5>,
    <ic2:resource:9>,
    <ic2:dust:28>,
    <galacticraftcore:canister>,
    <galacticraftcore:basic_item:7>,
    <ic2:cable:4>.withTag({type: 4 as byte, insulation: 0 as byte}),
    <ic2:cable:4>.withTag({type: 4 as byte, insulation: 1 as byte}),
    <ic2:filled_tin_can>,
    <ic2:crafting:10>,
    <mekanism:clump:4>,
    <mekanism:dirtydust:4>,
    <mekanism:shard:4>,
    <mekanism:crystal:4>,
    <chisel:blocktin>,
    <thermalfoundation:material:257>,
    <minecraft:golden_apple>,
    <minecraft:golden_apple:1>,
    <minecraft:gold_nugget>,
    <minecraft:gold_ingot>,
    <minecraft:gold_block>,
    <chisel:gold>,
    <chisel:blockgold>,
    <immersiveengineering:sheetmetal:10>,
    <immersiveengineering:sheetmetal_slab:10>,
    <ic2:crushed:1>,
    <ic2:purified:1>,
    <ic2:dust:7>,
    <ic2:dust:20>,
    <ic2:plate:2>,
    <ic2:plate:11>,
    <ic2:casing:2>,
    <ic2:cable:2>.withTag({type: 2 as byte, insulation: 0 as byte}),
    <ic2:cable:2>.withTag({type: 2 as byte, insulation: 1 as byte}),
    <ic2:cable:2>.withTag({type: 2 as byte, insulation: 2 as byte}),
    <ironchest:iron_gold_chest_upgrade>,
    <ironchest:gold_diamond_chest_upgrade>,
    <ironchest:silver_gold_chest_upgrade>,
    <ironchest:iron_gold_shulker_upgrade>,
    <ironchest:gold_diamond_shulker_upgrade>,
    <ironchest:silver_gold_shulker_upgrade>,
    <ironchest:iron_chest:1>,
    <mekanism:clump:1>,
    <mekanism:dirtydust:1>,
    <mekanism:shard:1>,
    <mekanism:crystal:1>,
    <mekanismtools:goldpaxel>,
    <thermalfoundation:material:25>,
    <openblocks:golden_eye:100>.withTag({}),
    <randomthings:ingredient:11>,
    <minecraft:golden_carrot>

]);

stageItems("Iron",[
    <minecraft:tripwire_hook>,
    <minecraft:hopper>,
    <minecraft:hopper_minecart>,
    <minecraft:tnt_minecart>,
    <minecraft:minecart>,
    <minecraft:compass>,
    <minecraft:bucket>,
    <minecraft:shears>,
    <minecraft:shield>,
    <chisel:chisel_iron>,
    <chisel:chisel_iron>,
    <minecraft:golden_rail>,
    <minecraft:detector_rail>,
    <minecraft:rail>,
    <minecraft:activator_rail>,
    <enderio:block_exit_rail>,
    <minecraft:sticky_piston>,
    <minecraft:piston>,
    <minecraft:iron_block>,
    <minecraft:iron_bars>,
    <minecraft:iron_trapdoor>,
    <minecraft:iron_door>,
    <minecraft:iron_shovel>,
    <minecraft:iron_pickaxe>,
    <minecraft:iron_axe>,
    <minecraft:iron_ingot>,
    <minecraft:iron_sword>,
    <ic2:te:46>,
    <immersiveengineering:drillhead:1>,
    <minecraft:iron_hoe>,
    <minecraft:iron_helmet>.withTag({}),
    <minecraft:iron_chestplate>.withTag({}),
    <minecraft:iron_leggings>.withTag({}),
    <minecraft:iron_boots>.withTag({}),
    <minecraft:iron_nugget>,
    <minecraft:iron_horse_armor>,
    <appliedenergistics2:material:49>,
    <betterbuilderswands:wandiron>,
    <ic2:dust:8>,
    <ic2:dust:21>,
    <ic2:plate:3>,
    <ic2:plate:12>,
    <ic2:casing:3>,
    <ic2:crafting:32>,
    <ic2:block_cutting_blade>,
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 0 as byte}),
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 1 as byte}),
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 2 as byte}),
    <ic2:cable:3>.withTag({type: 3 as byte, insulation: 3 as byte}),
    <ic2:rotor_iron>.withTag({advDmg: 0}),
    <ironchest:iron_gold_chest_upgrade>,
    <ironchest:iron_chest>,
    <ironchest:iron_shulker_box_white>,
    <ironchest:iron_shulker_box_orange>,
    <ironchest:iron_shulker_box_magenta>,
    <ironchest:iron_shulker_box_light_blue>,
    <ironchest:iron_shulker_box_yellow>,
    <ironchest:iron_shulker_box_lime>,
    <ironchest:iron_shulker_box_pink>,
    <ironchest:iron_shulker_box_gray>,
    <ironchest:iron_shulker_box_silver>,
    <ironchest:iron_shulker_box_cyan>,
    <ironchest:iron_shulker_box_purple>,
    <ironchest:iron_shulker_box_blue>,
    <ironchest:iron_shulker_box_brown>,
    <ironchest:iron_shulker_box_green>,
    <ironchest:iron_shulker_box_red>,
    <ironchest:iron_shulker_box_black>,
    <mekanism:enrichediron>,
    <mekanism:clump>,
    <mekanism:dirtydust>,
    <mekanism:shard>,
    <mekanism:crystal>,
    <mekanismtools:ironpaxel>,
    <mysticalmechanics:axle_iron>,
    <mysticalmechanics:gear_fan>,
    <randomthings:irondropper>,
    <galacticraftplanets:item_basic_asteroids:3>,
    <immersiveengineering:sheetmetal:9>,
    <immersiveengineering:sheetmetal_slab:9>,
    <immersiveengineering:material:1>,
    <immersiveengineering:material:8>,
    <ic2:te:132>.withTag({}),
    <ic2:te:112>,
    <ic2:scaffold:2>,
    <ic2:scaffold:3>,
    <ic2:fence>,
    <chisel:ironpane:*>
]);

stageItems("Steel",[
	<immersiveengineering:material:2>,
	<ic2:casing:5>,
	<immersiveengineering:sheetmetal:8>,
	<galacticraftcore:basic_item:9>,
	<immersiveengineering:material:23>,
	<extendedcrafting:singularity:24>,
	<galacticraftcore:steel_pole>,
	<immersiveengineering:storage_slab:8>,
	<immersiveengineering:sheetmetal_slab:8>,
	<immersiveengineering:metal_decoration1>,
	<immersiveengineering:metal_decoration1:1>,
	<immersiveengineering:metal_decoration1:2>,
	<immersiveengineering:metal_decoration1:3>,
	<immersiveengineering:metal_decoration2>,
	<immersiveengineering:metal_decoration2:1>,
	<immersiveengineering:metal_decoration2:7>,
	<immersiveengineering:metal_decoration1_slab:1>,
	<immersiveengineering:metal_decoration1_slab:2>,
	<immersiveengineering:metal_decoration1_slab:3>,
	<immersiveengineering:steel_scaffolding_stairs0>,
	<immersiveengineering:steel_scaffolding_stairs1>,
	<immersiveengineering:steel_scaffolding_stairs2>,
	<immersiveengineering:material:9>,
	<immersiveengineering:wirecoil:4>,
	<immersiveengineering:drillhead>,
	<immersiveengineering:steel_armor_feet>,
	<immersiveengineering:steel_armor_legs>,
	<immersiveengineering:steel_armor_chest>,
	<immersiveengineering:steel_armor_head>,
	<ic2:te:114>,
	<ic2:te:133>,
	<ic2:resource:8>,
	<ic2:ingot:5>,
	<ic2:plate:7>,
	<ic2:plate:16>,
	<ic2:crafting:30>,
	<ic2:crafting:33>,
	<ic2:block_cutting_blade:1>,
	<ic2:rotor_steel>.withTag({advDmg: 0}),
	<ic2:pipe:1>.withTag({size: 0 as byte, type: 1 as byte}),
	<ic2:pipe:1>.withTag({size: 1 as byte, type: 1 as byte}),
	<ic2:pipe:1>.withTag({size: 2 as byte, type: 1 as byte}),
	<ic2:pipe:1>.withTag({size: 3 as byte, type: 1 as byte}),
	<mekanism:otherdust:1>,
	<mekanism:basicblock:8>,
	<nuclearcraft:fission_reflector:1>,
	<nuclearcraft:turbine_rotor_blade_steel>,
	<nuclearcraft:alloy:15>,
	<nuclearcraft:part:12>,
	<nuclearcraft:fluid_steel>,
	<qmd:ingot_alloy:2>,
	<thermalfoundation:glass_alloy>,
	<thermalfoundation:material:224>,
	<thermalfoundation:material:288>,
	<tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 0 as short}}),
	<forge:bucketfilled>.withTag({FluidName: "steel", Amount: 1000})
]);

stageItems("Bronze",[
	<forge:bucketfilled>.withTag({FluidName: "bronze", Amount: 1000}),
	<thermalfoundation:material:291>,
	<ic2:plate>,
	<ic2:dust>,
	<ic2:resource:5>,
	<ic2:te:131>,
	<ic2:te:113>,
	<industrialupgrade:alloyplate>,
	<industrialupgrade:alloynugget>,
	<industrialupgrade:alloyingot>,
	<industrialupgrade:alloydoubleplate>,
	<industrialupgrade:alloycasing>,
	<extendedcrafting:singularity:19>,
	<mekanism:nugget:2>,
	<ic2:ingot:1>,
	<ic2:plate:9>,
	<ic2:rotor_bronze>,
	<ic2:crafting:42>,
	<ic2:casing>,
	<ic2:crafting:41>,
	<ic2:pipe>,
	<thermalfoundation:glass_alloy:3>,
	<ic2:dust:18>,
	<ic2:rotor_bronze>.withTag({advDmg: 0}),
	<ic2:pipe>.withTag({size: 2 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 0 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 3 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 1 as byte, type: 0 as byte}),
	<chisel:blockbronze>,
	<galacticraftcore:basic_item:10>
]);

stageItems("Multiblock Steam",[
	<mekanism:basicblock2:8>,
	<mekanism:basicblock:10>,
	<mekanism:basicblock2:7>,
	<mekanism:basicblock2:5>,
	<mekanism:basicblock2:6>
]);

stageItems("Singularity",[
	<extendedcrafting:singularity:*>
]);

stageItems("AE2 Basic", [
	<appliedenergistics2:controller>,
	<appliedenergistics2:drive>,
	<appliedenergistics2:chest>,
	<appliedenergistics2:inscriber>,
	<appliedenergistics2:quartz_growth_accelerator>,
	<appliedenergistics2:energy_acceptor>,
	<appliedenergistics2:condenser>,
	<appliedenergistics2:fluid_interface>,
	<appliedenergistics2:cell_workbench>,
	<appliedenergistics2:io_port>,
	<appliedenergistics2:vibration_chamber>,
	<appliedenergistics2:energy_cell>,
	<appliedenergistics2:energy_cell>.withTag({internalMaxPower: 200000.0, internalCurrentPower: 200000.0}),
	<appliedenergistics2:dense_energy_cell>,
	<appliedenergistics2:dense_energy_cell>.withTag({internalMaxPower: 1600000.0, internalCurrentPower: 1600000.0}),
	<appliedenergistics2:light_detector>,
	<appliedenergistics2:nether_quartz_wrench>,
	<appliedenergistics2:certus_quartz_wrench>,
	<appliedenergistics2:wireless_terminal>,
	<appliedenergistics2:wireless_terminal>.withTag({internalMaxPower: 1600000.0, internalCurrentPower: 1600000.0}),
	<appliedenergistics2:matter_cannon>,
	<appliedenergistics2:matter_cannon>.withTag({internalMaxPower: 200000.0, internalCurrentPower: 200000.0}),
	<appliedenergistics2:portable_cell>,
	<appliedenergistics2:portable_cell>.withTag({internalMaxPower: 20000.0, internalCurrentPower: 20000.0}),
	<appliedenergistics2:color_applicator>,
	<appliedenergistics2:color_applicator>.withTag({internalMaxPower: 20000.0, internalCurrentPower: 20000.0}),
	<appliedenergistics2:biometric_card>,
	<appliedenergistics2:memory_card>,
	<appliedenergistics2:network_tool>,
	<appliedenergistics2:view_cell>,
	<appliedenergistics2:storage_cell_1k>,
	<appliedenergistics2:storage_cell_4k>,
	<appliedenergistics2:storage_cell_16k>,
	<appliedenergistics2:storage_cell_64k>,
	<appliedenergistics2:fluid_storage_cell_1k>,
	<appliedenergistics2:fluid_storage_cell_1k>,
	<appliedenergistics2:fluid_storage_cell_4k>,
	<appliedenergistics2:fluid_storage_cell_16k>,
	<appliedenergistics2:fluid_storage_cell_64k>,
	<appliedenergistics2:spatial_storage_cell_2_cubed>,
	<appliedenergistics2:spatial_storage_cell_16_cubed>,
	<appliedenergistics2:spatial_storage_cell_128_cubed>,
	<appliedenergistics2:crystal_seed>.withTag({progress: 0}),
	<appliedenergistics2:crystal_seed:600>.withTag({progress: 600}),
	<appliedenergistics2:crystal_seed:1200>.withTag({progress: 1200}),
	<appliedenergistics2:crystal_seed>.withTag({progress: 200}),
	<appliedenergistics2:crystal_seed:600>.withTag({progress: 800}),
	<appliedenergistics2:crystal_seed:1200>.withTag({progress: 1400}),
	<appliedenergistics2:crystal_seed>.withTag({progress: 400}),
	<appliedenergistics2:crystal_seed:600>.withTag({progress: 1000}),
	<appliedenergistics2:crystal_seed:1200>.withTag({progress: 1600}),
	<appliedenergistics2:paint_ball:3>,
	<appliedenergistics2:paint_ball>,
	<appliedenergistics2:paint_ball:1>,
	<appliedenergistics2:paint_ball:2>,
	<appliedenergistics2:paint_ball:4>,
	<appliedenergistics2:paint_ball:5>,
	<appliedenergistics2:paint_ball:6>,
	<appliedenergistics2:paint_ball:7>,
	<appliedenergistics2:paint_ball:8>,
	<appliedenergistics2:paint_ball:9>,
	<appliedenergistics2:paint_ball:10>,
	<appliedenergistics2:paint_ball:11>,
	<appliedenergistics2:paint_ball:12>,
	<appliedenergistics2:paint_ball:13>,
	<appliedenergistics2:paint_ball:14>,
	<appliedenergistics2:paint_ball:15>,
	<appliedenergistics2:paint_ball:20>,
	<appliedenergistics2:paint_ball:21>,
	<appliedenergistics2:paint_ball:22>,
	<appliedenergistics2:paint_ball:23>,
	<appliedenergistics2:paint_ball:24>,
	<appliedenergistics2:paint_ball:25>,
	<appliedenergistics2:paint_ball:26>,
	<appliedenergistics2:paint_ball:27>,
	<appliedenergistics2:paint_ball:28>,
	<appliedenergistics2:paint_ball:29>,
	<appliedenergistics2:paint_ball:30>,
	<appliedenergistics2:paint_ball:31>,
	<appliedenergistics2:paint_ball:32>,
	<appliedenergistics2:paint_ball:33>,
	<appliedenergistics2:paint_ball:34>,
	<appliedenergistics2:paint_ball:35>,
	<appliedenergistics2:material:28>,
	<appliedenergistics2:material:44>,
	<appliedenergistics2:material:25>,
	<appliedenergistics2:material:52>,
	<appliedenergistics2:material:23>,
	<appliedenergistics2:material:13>,
	<appliedenergistics2:material:16>,
	<appliedenergistics2:material:27>,
	<appliedenergistics2:material:53>,
	<appliedenergistics2:material:29>,
	<appliedenergistics2:material:31>,
	<appliedenergistics2:material:26>,
	<appliedenergistics2:material:30>,
	<appliedenergistics2:material:34>,
	<appliedenergistics2:material:37>,
	<appliedenergistics2:material:33>,
	<appliedenergistics2:material:35>,
	<appliedenergistics2:material:32>,
	<appliedenergistics2:material:36>,
	<appliedenergistics2:material:38>,
	<appliedenergistics2:material:22>,
	<appliedenergistics2:material:15>,
	<appliedenergistics2:material:18>,
	<appliedenergistics2:material:6>,
	<appliedenergistics2:material:21>,
	<appliedenergistics2:material:3>,
	<appliedenergistics2:material:10>,
	<appliedenergistics2:material:12>,
	<appliedenergistics2:material:11>,
	<appliedenergistics2:material:48>,
	<appliedenergistics2:material:5>,
	<appliedenergistics2:material:19>,
	<appliedenergistics2:material:20>,
	<appliedenergistics2:material:47>,
	<appliedenergistics2:material:45>,
	<appliedenergistics2:material:41>,
	<appliedenergistics2:material:42>,
	<appliedenergistics2:part:300>,
	<appliedenergistics2:part:120>,
	<appliedenergistics2:part:20>,
	<appliedenergistics2:part:21>,
	<appliedenergistics2:part:22>,
	<appliedenergistics2:part:23>,
	<appliedenergistics2:part:24>,
	<appliedenergistics2:part:25>,
	<appliedenergistics2:part:26>,
	<appliedenergistics2:part:27>,
	<appliedenergistics2:part:28>,
	<appliedenergistics2:part:29>,
	<appliedenergistics2:part:30>,
	<appliedenergistics2:part:31>,
	<appliedenergistics2:part:32>,
	<appliedenergistics2:part:513>,
	<appliedenergistics2:part:514>,
	<appliedenergistics2:part:515>,
	<appliedenergistics2:part:516>,
	<appliedenergistics2:part:60>,
	<appliedenergistics2:part:61>,
	<appliedenergistics2:part:62>,
	<appliedenergistics2:part:63>,
	<appliedenergistics2:part:64>,
	<appliedenergistics2:part:65>,
	<appliedenergistics2:part:66>,
	<appliedenergistics2:part:67>,
	<appliedenergistics2:part:68>,
	<appliedenergistics2:part:69>,
	<appliedenergistics2:part:70>,
	<appliedenergistics2:part:71>,
	<appliedenergistics2:part:72>,
	<appliedenergistics2:part:73>,
	<appliedenergistics2:part:74>,
	<appliedenergistics2:part:75>,
	<appliedenergistics2:part:76>,
	<appliedenergistics2:part>,
	<appliedenergistics2:part:1>,
	<appliedenergistics2:part:2>,
	<appliedenergistics2:part:3>,
	<appliedenergistics2:part:4>,
	<appliedenergistics2:part:5>,
	<appliedenergistics2:part:6>,
	<appliedenergistics2:part:7>,
	<appliedenergistics2:part:8>,
	<appliedenergistics2:part:9>,
	<appliedenergistics2:part:10>,
	<appliedenergistics2:part:11>,
	<appliedenergistics2:part:12>,
	<appliedenergistics2:part:13>,
	<appliedenergistics2:part:14>,
	<appliedenergistics2:part:15>,
	<appliedenergistics2:part:16>,
	<appliedenergistics2:part:40>,
	<appliedenergistics2:part:41>,
	<appliedenergistics2:part:42>,
	<appliedenergistics2:part:43>,
	<appliedenergistics2:part:44>,
	<appliedenergistics2:part:45>,
	<appliedenergistics2:part:46>,
	<appliedenergistics2:part:47>,
	<appliedenergistics2:part:48>,
	<appliedenergistics2:part:49>,
	<appliedenergistics2:part:50>,
	<appliedenergistics2:part:51>,
	<appliedenergistics2:part:53>,
	<appliedenergistics2:part:54>,
	<appliedenergistics2:part:55>,
	<appliedenergistics2:part:56>,
	<appliedenergistics2:part:420>,
	<appliedenergistics2:part:360>,
	<appliedenergistics2:part:200>,
	<appliedenergistics2:part:260>,
	<appliedenergistics2:part:302>,
	<appliedenergistics2:part:261>,
	<appliedenergistics2:part:321>,
	<appliedenergistics2:part:241>,
	<appliedenergistics2:part:441>,
	<appliedenergistics2:part:281>,
	<appliedenergistics2:part:221>,
	<appliedenergistics2:part:520>,
	<appliedenergistics2:part:320>,
	<appliedenergistics2:part:301>,
	<appliedenergistics2:part:240>,
	<appliedenergistics2:part:100>,
	<appliedenergistics2:part:160>,
	<appliedenergistics2:part:469>,
	<appliedenergistics2:part:463>,
	<appliedenergistics2:part:465>,
	<appliedenergistics2:part:462>,
	<appliedenergistics2:part:467>,
	<appliedenergistics2:part:460>,
	<appliedenergistics2:part:461>,
	<appliedenergistics2:part:140>,
	<appliedenergistics2:part:180>,
	<appliedenergistics2:part:220>,
	<appliedenergistics2:part:400>,
	<appliedenergistics2:part:380>,
	<appliedenergistics2:part:80>,
	<ae2stuff:visualiser>,
	<ae2stuff:wireless_kit>,
	<ae2stuff:wireless>,
	<ae2stuff:inscriber>,
	<ae2stuff:grower>,
	<ae2stuff:visualiser>,
	<appliedenergistics2:wireless_access_point>,
	<appliedenergistics2:charger>,
	<appliedenergistics2:spatial_pylon>,
	<appliedenergistics2:spatial_io_port>,
	<appliedenergistics2:entropy_manipulator>.withTag({}),
	<appliedenergistics2:entropy_manipulator>.withTag({internalMaxPower: 200000.0, internalCurrentPower: 200000.0}),
	<appliedenergistics2:charged_staff>.withTag({}),
	<appliedenergistics2:charged_staff>.withTag({internalMaxPower: 8000.0, internalCurrentPower: 8000.0}),
	<appliedenergistics2:material:39>,
	<appliedenergistics2:material:24>,
	<appliedenergistics2:material:14>,
	<appliedenergistics2:material:17>,
	<appliedenergistics2:material:56>,
	<appliedenergistics2:material:54>,
	<appliedenergistics2:material:55>,
	<appliedenergistics2:material:57>,
	<appliedenergistics2:material:7>,
	<appliedenergistics2:material:8>,
	<appliedenergistics2:material:9>,
	<appliedenergistics2:material:43>,
	<appliedenergistics2:security_station>,
	<appliedenergistics2:part:33>,
	<appliedenergistics2:part:34>,
	<appliedenergistics2:part:35>,
	<appliedenergistics2:part:36>,
	<appliedenergistics2:part:500>,
	<appliedenergistics2:part:501>,
	<appliedenergistics2:part:502>,
	<appliedenergistics2:part:503>,
	<appliedenergistics2:part:504>,
	<appliedenergistics2:part:505>,
	<appliedenergistics2:part:506>,
	<appliedenergistics2:part:507>,
	<appliedenergistics2:part:508>,
	<appliedenergistics2:part:509>,
	<appliedenergistics2:part:510>,
	<appliedenergistics2:part:280>,
	<appliedenergistics2:part:52>,
	<appliedenergistics2:part:512>,
	<appliedenergistics2:part:511>,
	<appliedenergistics2:fluix_block>,
	<appliedenergistics2:fluix_stairs>,
	<appliedenergistics2:fluix_slab>


]);

stageItems("AE2 Autocrafting", [
	<appliedenergistics2:interface>,
	<appliedenergistics2:fluid_interface>,
	<appliedenergistics2:part:440>,
	<appliedenergistics2:part:480>,
	<appliedenergistics2:part:340>,
	<appliedenergistics2:encoded_pattern>,
	<appliedenergistics2:material:52>,
	<appliedenergistics2:molecular_assembler>,
	<appliedenergistics2:crafting_unit>,
	<appliedenergistics2:crafting_accelerator>,
	<appliedenergistics2:crafting_storage_1k>,
	<appliedenergistics2:crafting_storage_4k>,
	<appliedenergistics2:crafting_storage_16k>,
	<appliedenergistics2:crafting_storage_64k>,
	<ae2stuff:encoder>,
	<appliedenergistics2:crafting_monitor>,
	<ae2stuff:visualiser>
]);
