import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import mods.ItemStages;

function stageItems(stage as string, items as IItemStack[]) {
  for item in items {
    ItemStages.addItemStage(stage,item);
  }
}

stageItems("Steel",[
	<immersiveengineering:material:2>,
	<ic2:casing:5>,
	<immersiveengineering:sheetmetal:8>,
	<galacticraftcore:basic_item:9>,
	<immersiveengineering:material:23>,
	<tconstruct:pickaxe>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:hatchet>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:shovel>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:mattock>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:kama>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:hammer>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:excavator>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:lumberaxe>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:scythe>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:broadsword>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:longsword>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:shuriken>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:bolt>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:arrow>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:longbow>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:crossbow>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:shortbow>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:cleaver>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:battlesign>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<tconstruct:rapier>.withTag({TinkerData: {Materials: ["steel", "steel", "steel"]}}),
	<extendedcrafting:singularity:24>,
	<galacticraftcore:steel_pole>,
	<immersiveengineering:storage_slab:8>,
	<immersiveengineering:sheetmetal_slab:8>,
	<immersiveengineering:metal_decoration1>,
	<immersiveengineering:metal_decoration1:1>,
	<immersiveengineering:metal_decoration1:2>,
	<immersiveengineering:metal_decoration1:3>,
	<immersiveengineering:metal_decoration2>,
	<immersiveengineering:metal_decoration2:1>,
	<immersiveengineering:metal_decoration2:7>,
	<immersiveengineering:metal_decoration1_slab:1>,
	<immersiveengineering:metal_decoration1_slab:2>,
	<immersiveengineering:metal_decoration1_slab:3>,
	<immersiveengineering:steel_scaffolding_stairs0>,
	<immersiveengineering:steel_scaffolding_stairs1>,
	<immersiveengineering:steel_scaffolding_stairs2>,
	<immersiveengineering:material:9>,
	<immersiveengineering:wirecoil:4>,
	<immersiveengineering:drillhead>,
	<immersiveengineering:steel_armor_feet>,
	<immersiveengineering:steel_armor_legs>,
	<immersiveengineering:steel_armor_chest>,
	<immersiveengineering:steel_armor_head>,
	<ic2:te:114>,
	<ic2:te:133>,
	<ic2:resource:8>,
	<ic2:ingot:5>,
	<ic2:plate:7>,
	<ic2:plate:16>,
	<ic2:crafting:30>,
	<ic2:crafting:33>,
	<ic2:block_cutting_blade:1>,
	<ic2:rotor_steel>.withTag({advDmg: 0}),
	<ic2:pipe:1>.withTag({size: 0 as byte, type: 1 as byte}),
	<ic2:pipe:1>.withTag({size: 1 as byte, type: 1 as byte}),
	<ic2:pipe:1>.withTag({size: 2 as byte, type: 1 as byte}),
	<ic2:pipe:1>.withTag({size: 3 as byte, type: 1 as byte}),
	<mekanism:otherdust:1>,
	<mekanism:basicblock:8>,
	<nuclearcraft:fission_reflector:1>,
	<nuclearcraft:turbine_rotor_blade_steel>,
	<nuclearcraft:alloy:15>,
	<nuclearcraft:part:12>,
	<nuclearcraft:fluid_steel>,
	<qmd:ingot_alloy:2>,
	<thermalfoundation:glass_alloy>,
	<thermalfoundation:material:224>,
	<thermalfoundation:material:288>,
	<tconstruct:toolforge>.withTag({textureBlock: {id: "enderio:block_alloy", Count: 1 as byte, Damage: 0 as short}}),
	<forge:bucketfilled>.withTag({FluidName: "steel", Amount: 1000})
]);

stageItems("Bronze",[
	<forge:bucketfilled>.withTag({FluidName: "bronze", Amount: 1000}),
	<thermalfoundation:material:291>,
	<ic2:plate>,
	<ic2:dust>,
	<ic2:resource:5>,
	<ic2:te:131>,
	<ic2:te:113>,
	<industrialupgrade:alloyplate>,
	<industrialupgrade:alloynugget>,
	<industrialupgrade:alloyingot>,
	<industrialupgrade:alloydoubleplate>,
	<industrialupgrade:alloycasing>,
	<extendedcrafting:singularity:19>,
	<mekanism:nugget:2>,
	<ic2:ingot:1>,
	<ic2:plate:9>,
	<ic2:rotor_bronze>,
	<ic2:crafting:42>,
	<ic2:casing>,
	<ic2:crafting:41>,
	<ic2:pipe>,
	<thermalfoundation:glass_alloy:3>,
	<ic2:dust:18>,
	<ic2:rotor_bronze>.withTag({advDmg: 0}),
	<ic2:pipe>.withTag({size: 2 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 0 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 3 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 1 as byte, type: 0 as byte}),
	<chisel:blockbronze>,
	<galacticraftcore:basic_item:10>,
	<tconstruct:shard>.withTag({Material: "bronze"}),
	<tconstruct:sharpening_kit>.withTag({Material: "bronze"}),
	<tconstruct:pick_head>.withTag({Material: "bronze"}),
	<tconstruct:shovel_head>.withTag({Material: "bronze"}),
	<tconstruct:axe_head>.withTag({Material: "bronze"}),
	<tconstruct:sword_blade>.withTag({Material: "bronze"}),
	<tconstruct:broad_axe_head>.withTag({Material: "bronze"}),
	<tconstruct:large_sword_blade>.withTag({Material: "bronze"}),
	<tconstruct:hammer_head>.withTag({Material: "bronze"}),
	<tconstruct:arrow_head>.withTag({Material: "bronze"}),
	<tconstruct:bow_limb>.withTag({Material: "bronze"}),
	<tconstruct:knife_blade>.withTag({Material: "bronze"}),
	<tconstruct:large_plate>.withTag({Material: "bronze"}),
	<tconstruct:cross_guard>.withTag({Material: "bronze"}),
	<tconstruct:hand_guard>.withTag({Material: "bronze"}),
	<tconstruct:wide_guard>.withTag({Material: "bronze"}),
	<tconstruct:excavator_head>.withTag({Material: "bronze"}),
	<tconstruct:kama_head>.withTag({Material: "bronze"}),
	<tconstruct:scythe_head>.withTag({Material: "bronze"}),
	<tconstruct:pan_head>.withTag({Material: "bronze"}),
	<tconstruct:sign_head>.withTag({Material: "bronze"}),
	<tconstruct:tool_rod>.withTag({Material: "bronze"}),
	<tconstruct:tough_tool_rod>.withTag({Material: "bronze"}),
	<tconstruct:binding>.withTag({Material: "bronze"}),
	<tconstruct:tough_binding>.withTag({Material: "bronze"}),
	<tconstruct:pickaxe>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:hatchet>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:shovel>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:mattock>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:kama>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:hammer>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:excavator>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:lumberaxe>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:scythe>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:broadsword>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:longsword>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:shuriken>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:bolt>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:arrow>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:longbow>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:crossbow>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:shortbow>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:cleaver>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:battlesign>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:frypan>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}}),
	<tconstruct:rapier>.withTag({TinkerData: {Materials: ["bronze", "bronze", "bronze"]}})
]);

stageItems("Multiblock Boiler",[
	<mekanism:basicblock2:8>,
	<mekanism:basicblock:10>,
	<mekanism:basicblock2:7>,
	<mekanism:basicblock2:5>,
	<mekanism:basicblock2:6>
]);

stageItems("AE2 Basic", [
	<appliedenergistics2:controller>,
	<appliedenergistics2:drive>,
	<appliedenergistics2:chest>,
	<appliedenergistics2:inscriber>,
	<appliedenergistics2:quartz_growth_accelerator>,
	<appliedenergistics2:energy_acceptor>,
	<appliedenergistics2:condenser>,
	<appliedenergistics2:fluid_interface>,
	<appliedenergistics2:cell_workbench>,
	<appliedenergistics2:io_port>,
	<appliedenergistics2:vibration_chamber>,
	<appliedenergistics2:energy_cell>,
	<appliedenergistics2:energy_cell>.withTag({internalMaxPower: 200000.0, internalCurrentPower: 200000.0}),
	<appliedenergistics2:dense_energy_cell>,
	<appliedenergistics2:dense_energy_cell>.withTag({internalMaxPower: 1600000.0, internalCurrentPower: 1600000.0}),
	<appliedenergistics2:light_detector>,
	<appliedenergistics2:nether_quartz_wrench>,
	<appliedenergistics2:certus_quartz_wrench>,
	<appliedenergistics2:wireless_terminal>,
	<appliedenergistics2:wireless_terminal>.withTag({internalMaxPower: 1600000.0, internalCurrentPower: 1600000.0}),
	<appliedenergistics2:matter_cannon>,
	<appliedenergistics2:matter_cannon>.withTag({internalMaxPower: 200000.0, internalCurrentPower: 200000.0}),
	<appliedenergistics2:portable_cell>,
	<appliedenergistics2:portable_cell>.withTag({internalMaxPower: 20000.0, internalCurrentPower: 20000.0}),
	<appliedenergistics2:color_applicator>,
	<appliedenergistics2:color_applicator>.withTag({internalMaxPower: 20000.0, internalCurrentPower: 20000.0}),
	<appliedenergistics2:biometric_card>,
	<appliedenergistics2:memory_card>,
	<appliedenergistics2:network_tool>,
	<appliedenergistics2:view_cell>,
	<appliedenergistics2:storage_cell_1k>,
	<appliedenergistics2:storage_cell_4k>,
	<appliedenergistics2:storage_cell_16k>,
	<appliedenergistics2:storage_cell_64k>,
	<appliedenergistics2:fluid_storage_cell_1k>,
	<appliedenergistics2:fluid_storage_cell_1k>,
	<appliedenergistics2:fluid_storage_cell_4k>,
	<appliedenergistics2:fluid_storage_cell_16k>,
	<appliedenergistics2:fluid_storage_cell_64k>,
	<appliedenergistics2:spatial_storage_cell_2_cubed>,
	<appliedenergistics2:spatial_storage_cell_16_cubed>,
	<appliedenergistics2:spatial_storage_cell_128_cubed>,
	<appliedenergistics2:crystal_seed>.withTag({progress: 0}),
	<appliedenergistics2:crystal_seed:600>.withTag({progress: 600}),
	<appliedenergistics2:crystal_seed:1200>.withTag({progress: 1200}),
	<appliedenergistics2:crystal_seed>.withTag({progress: 200}),
	<appliedenergistics2:crystal_seed:600>.withTag({progress: 800}),
	<appliedenergistics2:crystal_seed:1200>.withTag({progress: 1400}),
	<appliedenergistics2:crystal_seed>.withTag({progress: 400}),
	<appliedenergistics2:crystal_seed:600>.withTag({progress: 1000}),
	<appliedenergistics2:crystal_seed:1200>.withTag({progress: 1600}),
	<appliedenergistics2:paint_ball:3>,
	<appliedenergistics2:paint_ball>,
	<appliedenergistics2:paint_ball:1>,
	<appliedenergistics2:paint_ball:2>,
	<appliedenergistics2:paint_ball:4>,
	<appliedenergistics2:paint_ball:5>,
	<appliedenergistics2:paint_ball:6>,
	<appliedenergistics2:paint_ball:7>,
	<appliedenergistics2:paint_ball:8>,
	<appliedenergistics2:paint_ball:9>,
	<appliedenergistics2:paint_ball:10>,
	<appliedenergistics2:paint_ball:11>,
	<appliedenergistics2:paint_ball:12>,
	<appliedenergistics2:paint_ball:13>,
	<appliedenergistics2:paint_ball:14>,
	<appliedenergistics2:paint_ball:15>,
	<appliedenergistics2:paint_ball:20>,
	<appliedenergistics2:paint_ball:21>,
	<appliedenergistics2:paint_ball:22>,
	<appliedenergistics2:paint_ball:23>,
	<appliedenergistics2:paint_ball:24>,
	<appliedenergistics2:paint_ball:25>,
	<appliedenergistics2:paint_ball:26>,
	<appliedenergistics2:paint_ball:27>,
	<appliedenergistics2:paint_ball:28>,
	<appliedenergistics2:paint_ball:29>,
	<appliedenergistics2:paint_ball:30>,
	<appliedenergistics2:paint_ball:31>,
	<appliedenergistics2:paint_ball:32>,
	<appliedenergistics2:paint_ball:33>,
	<appliedenergistics2:paint_ball:34>,
	<appliedenergistics2:paint_ball:35>,
	<appliedenergistics2:material:28>,
	<appliedenergistics2:material:44>,
	<appliedenergistics2:material:25>,
	<appliedenergistics2:material:52>,
	<appliedenergistics2:material:23>,
	<appliedenergistics2:material:13>,
	<appliedenergistics2:material:16>,
	<appliedenergistics2:material:27>,
	<appliedenergistics2:material:53>,
	<appliedenergistics2:material:29>,
	<appliedenergistics2:material:31>,
	<appliedenergistics2:material:26>,
	<appliedenergistics2:material:30>,
	<appliedenergistics2:material:34>,
	<appliedenergistics2:material:37>,
	<appliedenergistics2:material:33>,
	<appliedenergistics2:material:35>,
	<appliedenergistics2:material:32>,
	<appliedenergistics2:material:36>,
	<appliedenergistics2:material:38>,
	<appliedenergistics2:material:22>,
	<appliedenergistics2:material:15>,
	<appliedenergistics2:material:18>,
	<appliedenergistics2:material:6>,
	<appliedenergistics2:material:21>,
	<appliedenergistics2:material:3>,
	<appliedenergistics2:material:10>,
	<appliedenergistics2:material:12>,
	<appliedenergistics2:material:11>,
	<appliedenergistics2:material:48>,
	<appliedenergistics2:material:5>,
	<appliedenergistics2:material:19>,
	<appliedenergistics2:material:20>,
	<appliedenergistics2:material:47>,
	<appliedenergistics2:material:45>,
	<appliedenergistics2:material:41>,
	<appliedenergistics2:material:42>,
	<appliedenergistics2:part:300>,
	<appliedenergistics2:part:120>,
	<appliedenergistics2:part:20>,
	<appliedenergistics2:part:21>,
	<appliedenergistics2:part:22>,
	<appliedenergistics2:part:23>,
	<appliedenergistics2:part:24>,
	<appliedenergistics2:part:25>,
	<appliedenergistics2:part:26>,
	<appliedenergistics2:part:27>,
	<appliedenergistics2:part:28>,
	<appliedenergistics2:part:29>,
	<appliedenergistics2:part:30>,
	<appliedenergistics2:part:31>,
	<appliedenergistics2:part:32>,
	<appliedenergistics2:part:513>,
	<appliedenergistics2:part:514>,
	<appliedenergistics2:part:515>,
	<appliedenergistics2:part:516>,
	<appliedenergistics2:part:60>,
	<appliedenergistics2:part:61>,
	<appliedenergistics2:part:62>,
	<appliedenergistics2:part:63>,
	<appliedenergistics2:part:64>,
	<appliedenergistics2:part:65>,
	<appliedenergistics2:part:66>,
	<appliedenergistics2:part:67>,
	<appliedenergistics2:part:68>,
	<appliedenergistics2:part:69>,
	<appliedenergistics2:part:70>,
	<appliedenergistics2:part:71>,
	<appliedenergistics2:part:72>,
	<appliedenergistics2:part:73>,
	<appliedenergistics2:part:74>,
	<appliedenergistics2:part:75>,
	<appliedenergistics2:part:76>,
	<appliedenergistics2:part>,
	<appliedenergistics2:part:1>,
	<appliedenergistics2:part:2>,
	<appliedenergistics2:part:3>,
	<appliedenergistics2:part:4>,
	<appliedenergistics2:part:5>,
	<appliedenergistics2:part:6>,
	<appliedenergistics2:part:7>,
	<appliedenergistics2:part:8>,
	<appliedenergistics2:part:9>,
	<appliedenergistics2:part:10>,
	<appliedenergistics2:part:11>,
	<appliedenergistics2:part:12>,
	<appliedenergistics2:part:13>,
	<appliedenergistics2:part:14>,
	<appliedenergistics2:part:15>,
	<appliedenergistics2:part:16>,
	<appliedenergistics2:part:40>,
	<appliedenergistics2:part:41>,
	<appliedenergistics2:part:42>,
	<appliedenergistics2:part:43>,
	<appliedenergistics2:part:44>,
	<appliedenergistics2:part:45>,
	<appliedenergistics2:part:46>,
	<appliedenergistics2:part:47>,
	<appliedenergistics2:part:48>,
	<appliedenergistics2:part:49>,
	<appliedenergistics2:part:50>,
	<appliedenergistics2:part:51>,
	<appliedenergistics2:part:53>,
	<appliedenergistics2:part:54>,
	<appliedenergistics2:part:55>,
	<appliedenergistics2:part:56>,
	<appliedenergistics2:part:420>,
	<appliedenergistics2:part:360>,
	<appliedenergistics2:part:200>,
	<appliedenergistics2:part:260>,
	<appliedenergistics2:part:302>,
	<appliedenergistics2:part:261>,
	<appliedenergistics2:part:321>,
	<appliedenergistics2:part:241>,
	<appliedenergistics2:part:441>,
	<appliedenergistics2:part:281>,
	<appliedenergistics2:part:221>,
	<appliedenergistics2:part:520>,
	<appliedenergistics2:part:320>,
	<appliedenergistics2:part:301>,
	<appliedenergistics2:part:240>,
	<appliedenergistics2:part:100>,
	<appliedenergistics2:part:160>,
	<appliedenergistics2:part:469>,
	<appliedenergistics2:part:463>,
	<appliedenergistics2:part:465>,
	<appliedenergistics2:part:462>,
	<appliedenergistics2:part:467>,
	<appliedenergistics2:part:460>,
	<appliedenergistics2:part:461>,
	<appliedenergistics2:part:140>,
	<appliedenergistics2:part:180>,
	<appliedenergistics2:part:220>,
	<appliedenergistics2:part:400>,
	<appliedenergistics2:part:380>,
	<appliedenergistics2:part:80>,
	<ae2stuff:visualiser>,
	<ae2stuff:wireless_kit>,
	<ae2stuff:wireless>,
	<ae2stuff:inscriber>,
	<ae2stuff:grower>,
	<ae2stuff:visualiser>,
	<appliedenergistics2:wireless_access_point>,
	<appliedenergistics2:charger>,
	<appliedenergistics2:spatial_pylon>,
	<appliedenergistics2:spatial_io_port>,
	<appliedenergistics2:entropy_manipulator>.withTag({}),
	<appliedenergistics2:entropy_manipulator>.withTag({internalMaxPower: 200000.0, internalCurrentPower: 200000.0}),
	<appliedenergistics2:charged_staff>.withTag({}),
	<appliedenergistics2:charged_staff>.withTag({internalMaxPower: 8000.0, internalCurrentPower: 8000.0}),
	<appliedenergistics2:material:39>,
	<appliedenergistics2:material:24>,
	<appliedenergistics2:material:14>,
	<appliedenergistics2:material:17>,
	<appliedenergistics2:material:56>,
	<appliedenergistics2:material:54>,
	<appliedenergistics2:material:55>,
	<appliedenergistics2:material:57>,
	<appliedenergistics2:material:7>,
	<appliedenergistics2:material:8>,
	<appliedenergistics2:material:9>,
	<appliedenergistics2:material:43>,
	<appliedenergistics2:security_station>,
	<appliedenergistics2:part:33>,
	<appliedenergistics2:part:34>,
	<appliedenergistics2:part:35>,
	<appliedenergistics2:part:36>,
	<appliedenergistics2:part:500>,
	<appliedenergistics2:part:501>,
	<appliedenergistics2:part:502>,
	<appliedenergistics2:part:503>,
	<appliedenergistics2:part:504>,
	<appliedenergistics2:part:505>,
	<appliedenergistics2:part:506>,
	<appliedenergistics2:part:507>,
	<appliedenergistics2:part:508>,
	<appliedenergistics2:part:509>,
	<appliedenergistics2:part:510>,
	<appliedenergistics2:part:280>,
	<appliedenergistics2:part:52>,
	<appliedenergistics2:part:512>,
	<appliedenergistics2:part:511>,
	<appliedenergistics2:fluix_block>,
	<appliedenergistics2:fluix_stairs>,
	<appliedenergistics2:fluix_slab>


]);

stageItems("AE2 Autocrafting", [
	<appliedenergistics2:interface>,
	<appliedenergistics2:fluid_interface>,
	<appliedenergistics2:part:440>,
	<appliedenergistics2:part:480>,
	<appliedenergistics2:part:340>,
	<appliedenergistics2:encoded_pattern>,
	<appliedenergistics2:material:52>,
	<appliedenergistics2:molecular_assembler>,
	<appliedenergistics2:crafting_unit>,
	<appliedenergistics2:crafting_accelerator>,
	<appliedenergistics2:crafting_storage_1k>,
	<appliedenergistics2:crafting_storage_4k>,
	<appliedenergistics2:crafting_storage_16k>,
	<appliedenergistics2:crafting_storage_64k>,
	<ae2stuff:encoder>,
	<appliedenergistics2:crafting_monitor>,
	<ae2stuff:visualiser>
]);
 
ItemStages.stageModItems("Trinity", "trinity");
ItemStages.stageModItems("Quantum Tech", "qmd");