import mods.jei.JEI;

JEI.hideCategory("minecraft.fuel");
JEI.hideCategory("gen_stone");
JEI.hideCategory("lava_gen");
JEI.hideCategory("neutron_generator");
JEI.hideCategory("gen_obsidian");
JEI.hideCategory("assamplerscrap");
JEI.hideCategory("comb_macerator");
JEI.hideCategory("tconstruct.dryingrack");
JEI.hideCategory("ie.arcFurnace.recycling");
JEI.hideCategory("ie.bottlingMachine");
JEI.hideCategory("galacticraft.astroMiner");
JEI.hideCategory("planetprogression.satellite.builder");
JEI.hideCategory("petrified_burn_time");
JEI.hideCategory("ORE_WASHER");
JEI.hideCategory("ORE_FERMENTER");
JEI.hideCategory("ORE_SIEVE");
JEI.hideCategory("galacticraft.buggy");
JEI.hideCategory("StirlingGenerator");
JEI.hideCategory("EIOWO");
JEI.hideCategory("nuclearcraft_pebble_fission");
JEI.hideCategory("nuclearcraft_heat_exchanger");
JEI.hideCategory("nuclearcraft_condenser");
JEI.hideCategory("thermalexpansion.steam");
JEI.hideCategory("thermalexpansion.magmatic");
JEI.hideCategory("thermalexpansion.compression");
JEI.hideCategory("thermalexpansion.reactant");
JEI.hideCategory("thermalexpansion.reactant_elemental");
JEI.hideCategory("thermalexpansion.enervation");
JEI.hideCategory("thermalexpansion.numismatic");
JEI.hideCategory("thermalexpansion.numismatic_gem");
JEI.hideCategory("notreepunching.knife");
JEI.hideCategory("SolarPanel");
JEI.hideCategory("bioreactor_accepted_items");
JEI.hideCategory("Imbuing");
JEI.hideCategory("planetprogression.satellite.rocket");
JEI.hideCategory("galacticraft.gas_liquefier");
JEI.hideCategory("galacticraft.refinery");
JEI.hideCategory("CombustionGenerator");
JEI.hideCategory("ZombieGenerator");
JEI.hideCategory("EnderGenerator");
JEI.hideCategory("LavaGenerator");
JEI.hideCategory("electrolyzer");
JEI.hideCategory("galacticraft.methaneSynthesizer");
JEI.hideCategory("qmd.atmosphere_collector");


