#priority 9000
import crafttweaker.item.IItemStack;
import mods.jei.JEI;
function hideItems(items as IItemStack[]) {
	for item in items {
		JEI.removeAndHide(item);
	}
}
hideItems([
    <randomthings:runepattern>,
    <randomthings:goldencompass>,
    <randomthings:ingredient:8>,
    <randomthings:ingredient:7>,
    <randomthings:ingredient:10>,
    <randomthings:redstoneremote>,
    <randomthings:flootoken>,
    <randomthings:portkey>,
    <randomthings:lotusseeds>,
    <randomthings:soundpattern>,
    <randomthings:soundrecorder>,
    <randomthings:portablesounddampener>.withTag({}),
    <randomthings:escaperope>,
    <randomthings:weatheregg>,
    <randomthings:weatheregg:1>,
    <randomthings:weatheregg:2>,
	<appliedenergistics2:creative_energy_cell>,
	<appliedenergistics2:creative_storage_cell>.withTag({}),
	<galacticraftcore:infinite_battery>,
	<draconicevolution:draconium_capacitor:2>,
	<galacticraftcore:dungeonfinder>,
	<enderio:block_decoration2:4>,
	<enderio:block_buffer:3>,
	<enderio:block_creative_spawner>,
	<enderio:block_cap_bank>.withTag({"enderio:energy": 50000000}),
	<thermalinnovation:saw:32000>.withTag({Energy: 600000, Mode: 4}),
	<thermalinnovation:drill:32000>.withTag({Energy: 600000, Mode: 4}),
	<thermalfoundation:upgrade:256>,
	<thermalexpansion:satchel:32000>.withTag({Accessible: 1 as byte}),
	<thermalexpansion:reservoir:32000>.withTag({}),
	<thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}),
	<theoneprobe:creativeprobe>,
	<reactorbuilder:creativereactorbuilder>,
	<randomthings:creativeplayerinterface>,
	<ic2:te:86>,
	<mekanism:basicblock:6>.withTag({tier: 4}),
	<mekanism:machineblock2:11>.withTag({tier: 4}),
	<mekanism:energycube>.withTag({tier: 4}),
	<mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}),
	<mekanism:gastank>.withTag({tier: 4}),
	<mysticalmechanics:creative_mech_source>,
	<qmd:creative_particle_source>,
	<rftools:powercell_creative>,
	<immersiveengineering:metal_device0:3>,
	<galacticraftplanets:rocket_t3:4>,
	<galacticraftplanets:rocket_t2:14>,
	<galacticraftcore:infinite_oxygen>,
	<draconicevolution:creative_exchanger>,
	<draconicevolution:creative_rf_source>,
	<galacticraftplanets:rocket_t2:4>,
	<galacticraftcore:rocket_t1:4>,
	<galacticraftcore:concealed_detector>,
	<thermalinnovation:magnet:32000>.withTag({Energy: 600000}),
	<thermalinnovation:injector:32000>.withTag({}),
	<thermalinnovation:quiver:32000>.withTag({}),
	<tconstruct:materials:50>,
	<rftools:syringe>,
	<rftools:shield_template_block:*>,
	<rftools:spawner>,
	<rftools:powercell>,
	<rftools:powercell_advanced>,
	<rftools:powercell_creative>,
	<rftools:powercell_simple>,
	<rftools:endergenic>,
	<rftools:pearl_injector>,
	<rftools:shield_block1>,
	<rftools:shield_block2>,
	<rftools:shield_block3>,
	<rftools:shield_block4>,
	<rftools:matter_booster>,
	<rftools:notick_invisible_shield_block_opaque>,
	<rftools:invisible_shield_block_opaque>,
	<rftools:notick_invisible_shield_block>,
	<rftools:invisible_shield_block>,
	<rftools:matter_booster>,
	<rftools:matter_transmitter>,
	<rftools:matter_receiver>,
	<rftools:remote_storage>,
	<rftools:notick_camo_shield_block_opaque>,
	<rftools:notick_solid_shield_block_opaque>,
	<rftools:notick_camo_shield_block>,
	<rftools:notick_solid_shield_block>,
	<rftools:camo_shield_block_opaque>,
	<rftools:solid_shield_block_opaque>,
	<rftools:camo_shield_block>,
	<rftools:solid_shield_block>,

	#TRISO FUEL
	<nuclearcraft:fuel_uranium:12>,
	<nuclearcraft:fuel_neptunium>,
	<nuclearcraft:fuel_neptunium:4>,
	<nuclearcraft:fuel_plutonium>,
	<nuclearcraft:fuel_plutonium:4>,
	<nuclearcraft:fuel_plutonium:8>,
	<nuclearcraft:fuel_plutonium:12>,
	<nuclearcraft:fuel_mixed>,
	<nuclearcraft:fuel_mixed:4>,
	<nuclearcraft:fuel_thorium>,
	<nuclearcraft:fuel_uranium>,
	<nuclearcraft:fuel_uranium:4>,
	<nuclearcraft:fuel_uranium:8>,
	<nuclearcraft:fuel_americium>,
	<nuclearcraft:fuel_americium:4>,
	<nuclearcraft:fuel_curium>,
	<nuclearcraft:fuel_curium:4>,
	<nuclearcraft:fuel_curium:8>,
	<nuclearcraft:fuel_curium:12>,
	<nuclearcraft:fuel_curium:16>,
	<nuclearcraft:fuel_curium:20>,
	<nuclearcraft:fuel_berkelium>,
	<nuclearcraft:fuel_berkelium:4>,
	<nuclearcraft:fuel_californium>,
	<nuclearcraft:fuel_californium:4>,
	<nuclearcraft:fuel_californium:8>,
	<nuclearcraft:fuel_californium:12>,
	<nuclearcraft:depleted_fuel_thorium>,
	<nuclearcraft:depleted_fuel_uranium>,
	<nuclearcraft:depleted_fuel_uranium:4>,
	<nuclearcraft:depleted_fuel_uranium:4>,
	<nuclearcraft:depleted_fuel_uranium:8>,
	<nuclearcraft:depleted_fuel_uranium:12>,
	<nuclearcraft:depleted_fuel_neptunium>,
	<nuclearcraft:depleted_fuel_neptunium:4>,
	<nuclearcraft:depleted_fuel_plutonium>,
	<nuclearcraft:depleted_fuel_plutonium:4>,
	<nuclearcraft:depleted_fuel_plutonium:8>,
	<nuclearcraft:depleted_fuel_plutonium:12>,
	<nuclearcraft:depleted_fuel_mixed:4>,
	<nuclearcraft:depleted_fuel_mixed>,
	<nuclearcraft:depleted_fuel_americium>,
	<nuclearcraft:depleted_fuel_americium:4>,
	<nuclearcraft:depleted_fuel_curium>,
	<nuclearcraft:depleted_fuel_curium:4>,
	<nuclearcraft:depleted_fuel_curium:8>,
	<nuclearcraft:depleted_fuel_curium:12>,
	<nuclearcraft:depleted_fuel_curium:16>,
	<nuclearcraft:depleted_fuel_curium:20>,
	<nuclearcraft:depleted_fuel_berkelium>,
	<nuclearcraft:depleted_fuel_berkelium:4>,
	<nuclearcraft:depleted_fuel_californium>,
	<nuclearcraft:depleted_fuel_californium:4>,
	<nuclearcraft:depleted_fuel_californium:8>,
	<nuclearcraft:depleted_fuel_californium:12>,
	<qmd:depleted_fuel_copernicium>,
	<qmd:fuel_copernicium>,
	<tconstruct:clay_cast>,
	<industrialupgrade:basemachine:5>,

	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:hand_guard"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:pick_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:axe_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:shard"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:shovel_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:tough_tool_rod"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:bow_string"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:scythe_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:sword_blade"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:sharpening_kit"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:wide_guard"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:large_plate"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:large_sword_blade"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:arrow_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:tool_rod"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:binding"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:excavator_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:hammer_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:pan_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:cross_guard"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:sign_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:tough_binding"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:broad_axe_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:bow_limb"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:kama_head"}),
	<tconstruct:clay_cast>.withTag({PartType: "tconstruct:knife_blade"}),
	<tconstruct:cast>.withTag({PartType: "tconstruct:sign_head"}),
	<tconstruct:cast>.withTag({PartType: "tconstruct:pan_head"}),
	<tconstruct:frypan>.withTag({StatsOriginal: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 6.5 as float, FreeModifiers: 3, Durability: 310, HarvestLevel: 2, Attack: 2.25 as float}, Stats: {AttackSpeedMultiplier: 1.1 as float, MiningSpeed: 6.5 as float, FreeModifiers: 3, Durability: 310, HarvestLevel: 2, Attack: 2.25 as float}, Special: {Categories: ["weapon", "tool"]}, TinkerData: {Materials: ["electrical_steel", "electrical_steel"], Modifiers: ["toolleveling"]}, Modifiers: [{identifier: "lightweight", color: -5658199, level: 1}, {identifier: "shocking", color: -5658199, level: 1}, {identifier: "toolleveling", color: 16777215, level: 1}], Traits: ["lightweight", "shocking", "toolleveling"]}),
	<tconstruct:pan_head>.withTag({Material: "electrical_steel"}),
	<tconstruct:sign_head>.withTag({Material: "electrical_steel"}),
	<tconstruct:battlesign>.withTag({StatsOriginal: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 6.5 as float, FreeModifiers: 3, Durability: 310, HarvestLevel: 2, Attack: 2.25 as float}, Stats: {AttackSpeedMultiplier: 1.1 as float, MiningSpeed: 6.5 as float, FreeModifiers: 3, Durability: 310, HarvestLevel: 2, Attack: 2.25 as float}, Special: {Categories: ["weapon", "tool"]}, TinkerData: {Materials: ["electrical_steel", "electrical_steel"], Modifiers: ["toolleveling"]}, Modifiers: [{identifier: "lightweight", color: -5658199, level: 1}, {identifier: "shocking", color: -5658199, level: 1}, {identifier: "toolleveling", color: 16777215, level: 1}], Traits: ["lightweight", "shocking", "toolleveling"]}),
	<tconstruct:frypan>.withTag({StatsOriginal: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 12.0 as float, FreeModifiers: 3, Durability: 546, HarvestLevel: 4, Attack: 4.1 as float}, display: {NoRename: 1 as byte, Name: "Bane of Pigs"}, Stats: {AttackSpeedMultiplier: 1.0 as float, MiningSpeed: 999999.0 as float, FreeModifiers: 0, Durability: 999999, HarvestLevel: 4, Attack: 999999.0 as float}, Special: {Categories: ["weapon", "tool"]}, TinkerData: {UsedModifiers: 5, Materials: ["slime", "cobalt"], Modifiers: ["toolleveling", "infitool", "fiery"]}, Modifiers: [{identifier: "slimey_green", color: -8206221, level: 1}, {identifier: "momentum", color: -14122284, level: 1}, {identifier: "toolleveling", color: 16777215, level: 1}, {identifier: "infitool", color: 16777215, level: 1}, {identifier: "fiery", current: 125, color: 15375922, level: 5, max: 125, extraInfo: "124 / 125"}], Traits: ["slimey_green", "momentum", "toolleveling", "infitool", "fiery"]}),
	<tconstruct:sharpening_kit>.withTag({Material: "electrical_steel"}),
	<tconstruct:pattern>.withTag({PartType: "tconstruct:sharpening_kit"}),
	<tconstruct:cast>.withTag({PartType: "tconstruct:sharpening_kit"}),

	<mekanism:nugget:5>,
	<immersiveengineering:metal:20>,
	<thermalfoundation:material:192>,

	<immersiveengineering:metal:22>,

	<thermalfoundation:material:198>,

	<thermalfoundation:material:197>,
	<immersiveengineering:metal:24>,

	<immersiveengineering:metal:23>,
	<thermalfoundation:material:194>,

	<immersiveengineering:metal:28>,
	<mekanism:nugget:4>,

	<thermalfoundation:material:227>,
	<mekanism:nugget:2>,

	<thermalfoundation:material:226>,

	<thermalfoundation:material:225>,
	<immersiveengineering:metal:27>,

	<immersiveengineering:storage:5>,
	<nuclearcraft:ingot_block:4>,

	<thermalfoundation:storage>,
	<mekanism:basicblock:12>,
	<nuclearcraft:ingot_block>,
	<immersiveengineering:storage>,
	<galacticraftcore:basic_block_core:9>,

	<galacticraftplanets:venus:12>,
	<immersiveengineering:storage:2>,
	<nuclearcraft:ingot_block:2>,
	<thermalfoundation:storage:3>,

	<galacticraftcore:basic_block_core:10>,
	<mekanism:basicblock:13>,
	<nuclearcraft:ingot_block:1>,
	<thermalfoundation:storage:1>,

	<thermalfoundation:storage:6>,

	<immersiveengineering:storage:4>,
	<thermalfoundation:storage:5>,

	<immersiveengineering:storage:3>,
	<industrialupgrade:baseblockingot:14>,
	<nuclearcraft:ingot_block:13>,
	<thermalfoundation:storage:2>,

	<nuclearcraft:ingot_block:7>,

	<thermalfoundation:storage_alloy>,
	<mekanism:basicblock:5>,
	<immersiveengineering:storage:8>,

	<thermalfoundation:storage_alloy:3>,
	<mekanism:basicblock:1>,
	<industrialupgrade:baseblockalloy>,

	<thermalfoundation:storage_alloy:2>,

	<immersiveengineering:storage:7>,
	<thermalfoundation:storage_alloy:1>,
	<nuclearcraft:dust:4>,
	<immersiveengineering:metal:14>,
	<ic2:crushed:6>,

	<enderio:item_material:26>,
	<immersiveengineering:metal:9>,
	<thermalfoundation:material:64>,
	<ic2:crushed>,

	<immersiveengineering:metal:11>,
	<thermalfoundation:material:67>,
	<mekanism:dust:6>,

	<enderio:item_material:27>,

	<qmd:dust:10>,
	<thermalfoundation:material:70>,
	<industrialupgrade:crushed:9>,

	<immersiveengineering:metal:13>,
	<thermalfoundation:material:69>,

	<thermalfoundation:material:66>,
	<immersiveengineering:metal:12>,
	<industrialupgrade:itemdust:14>,
	<mekanism:dust:5>,

	<nuclearcraft:dust:7>,

	<thermalfoundation:material:96>,
	<immersiveengineering:metal:17>,

	<thermalfoundation:material:99>,
	<industrialupgrade:alloydust>,

	<thermalfoundation:material:98>,

	<thermalfoundation:material:97>,
	<immersiveengineering:metal:16>,
	<immersiveengineering:metal:30>,
	<thermalfoundation:material:320>,

	<thermalfoundation:material:323>,
	<immersiveengineering:metal:32>,

	<thermalfoundation:material:326>,

	<thermalfoundation:material:325>,
	<immersiveengineering:metal:34>,

	<thermalfoundation:material:322>,

	<thermalfoundation:material:352>,
	<immersiveengineering:metal:38>,


	<thermalfoundation:material:355>,

	<thermalfoundation:material:354>,

	<thermalfoundation:material:353>,
	<immersiveengineering:metal:37>,

	<thermalfoundation:material:65>,
	<nuclearcraft:dust:1>,
	<mekanism:dust:4>,
	<nuclearcraft:dust:2>,

	//coins
	<thermalfoundation:coin:*>,

	<thermalfoundation:material>,
	<immersiveengineering:metal:18>,
	<enderio:item_material:24>,
	<appliedenergistics2:material:49>,

	<tconstruct:slime_vine_purple>,
	<tconstruct:slime_vine_purple_mid>,
	<tconstruct:slime_vine_purple_end>,
	<tconstruct:slime_vine_blue>,
	<tconstruct:slime_vine_blue_mid>,
	<tconstruct:slime_vine_blue_end>,
	<tconstruct:slime_grass_tall:8>,
	<tconstruct:slime_grass_tall:4>,
	<tconstruct:slime_grass_tall>,
	<tconstruct:slime_leaves:2>,
	<tconstruct:slime_leaves:1>,
	<minecraft:tallgrass:1>,
	<minecraft:double_plant:2>,
	<minecraft:record_13>,
	<minecraft:record_cat>,
	<minecraft:record_blocks>,
	<minecraft:record_chirp>,
	<minecraft:record_far>,
	<minecraft:record_mall>,
	<minecraft:record_mellohi>,
	<minecraft:record_stal>,
	<minecraft:record_strad>,
	<minecraft:record_ward>,
	<minecraft:record_11>,
	<minecraft:record_wait>,
	<minecraft:command_block>,
	<minecraft:barrier>,
	<minecraft:grass_path>,
	<minecraft:repeating_command_block>,
	<minecraft:chain_command_block>,
	<minecraft:structure_void>,
	<minecraft:structure_block>,
	<minecraft:chainmail_helmet>,
	<minecraft:chainmail_chestplate>,
	<minecraft:chainmail_leggings>,
	<minecraft:chainmail_boots>
]);