#priority 9999
import mods.jei.JEI;
import crafttweaker.item.IItemStack;

function removeRecipes(items as IItemStack[]) {
	for item in items {
		recipes.remove(item);
	}
}

function removeRecipesByName(items as string[]) {
	for item in items {
		recipes.removeByRecipeName(item);
	}
}

function removeAndHideItems(items as IItemStack[]) {
	for item in items {
		recipes.remove(item);
		JEI.removeAndHide(item);
	}
}

function removeAndHideAndFurnaceItems(items as IItemStack[]) {
	for item in items {
		recipes.remove(item);
		JEI.removeAndHide(item);
		furnace.remove(item);
	}
}

removeRecipesByName([
    "minecraft:iron_helmet",
    "minecraft:iron_boots",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "mekanismgenerators:generator_7"
]);

removeAndHideItems([
    <mekanism:nugget:2>,
    <mekanism:nugget:6>,
    <tconstruct:nuggets>,
    <galacticraftplanets:asteroids_block:7>,
    <ncsteamadditions:ingot>,
    <ncsteamadditions:dust>,
    <ncsteamadditions:ingot_block>,
    <ncsteamadditions:ore>,
    <draconicevolution:rain_sensor>,
    <draconicevolution:entity_detector>,
    <mutantbeasts:mutant_skeleton_chestplate>.withTag({}),
    <thermaldynamics:duct_32>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32>,
    <thermaldynamics:duct_32:1>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:1>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:1>,
    <thermaldynamics:duct_32:2>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:2>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:2>,
    <thermaldynamics:duct_32:3>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:3>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:3>,
    <thermaldynamics:duct_32:4>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:4>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:4>,
    <thermaldynamics:duct_32:5>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:5>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:5>,
    <thermaldynamics:duct_32:6>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:6>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:6>,
    <thermaldynamics:duct_32:7>.withTag({DenseType: 2 as byte}),
    <thermaldynamics:duct_32:7>.withTag({DenseType: 1 as byte}),
    <thermaldynamics:duct_32:7>,
    <thermalinnovation:drill>.withTag({Energy: 40000, Mode: 1}),
    <thermalinnovation:saw>.withTag({Energy: 40000, Mode: 1}),
    <thermalinnovation:magnet>.withTag({Energy: 40000}),
    <thermalinnovation:drill:2>.withTag({Energy: 240000, Mode: 2}),
    <thermalinnovation:drill:3>.withTag({Energy: 400000, Mode: 3}),
    <thermalinnovation:drill:4>.withTag({Energy: 600000, Mode: 4}),
    <thermalinnovation:saw:1>.withTag({Energy: 120000, Mode: 2}),
    <thermalinnovation:saw:2>.withTag({Energy: 240000, Mode: 2}),
    <thermalinnovation:saw:3>.withTag({Energy: 400000, Mode: 3}),
    <thermalinnovation:saw:4>.withTag({Energy: 600000, Mode: 4}),
    <thermalinnovation:magnet:1>.withTag({Energy: 120000}),
    <thermalinnovation:magnet:2>.withTag({Energy: 240000}),
    <thermalinnovation:magnet:3>.withTag({Energy: 400000}),
    <thermalinnovation:magnet:4>.withTag({Energy: 600000}),
    <ic2:te:4>,
    <ic2:te:7>,
    <ic2:te:9>,
    <ic2:te:19>,
    <ic2:te:93>,
    <ic2:te:92>,
    <thermalfoundation:storage:4>,
    <nuclearcraft:ingot_block:12>,
    <nuclearcraft:ingot:12>,
    <immersiveengineering:material:3>,
    <galacticraftplanets:walkway:1>,
    <ic2:jetpack:27>.withTag({}),
    <ic2:jetpack:1>.withTag({Fluid: {FluidName: "ic2biogas", Amount: 30000}}),
    <ic2:boat>,
    <ic2:boat:1>,
    <ic2:boat:2>,
    <ic2:boat:3>,
    <ic2:chainsaw:26>.withTag({}),
    <ic2:chainsaw>.withTag({charge: 30000.0}),
    <ic2:diamond_drill:26>.withTag({}),
    <ic2:diamond_drill>.withTag({charge: 30000.0}),
    <ic2:drill:26>.withTag({}),
    <ic2:drill:26>.withTag({}),
    <ic2:drill>.withTag({charge: 30000.0}),
    <ic2:booze_mug>,
    <ic2:barrel>,
    <thermalfoundation:material:32>,
    <immersiveengineering:metal:39>,
    <betterbuilderswands:wandunbreakable:14>,
    <betterbuilderswands:wandunbreakable:13>,
    <betterbuilderswands:wandunbreakable:12>,
    <randomthings:floosign>,
    <ic2:te:2>,
    <galacticraftcore:basic_item:5>,
    <immersiveengineering:metal:1>,
    <thermalfoundation:material:132>,
    <thermalfoundation:material:196>,
    <thermalfoundation:material:321>,
    <thermalfoundation:material:356>,
    <thermalfoundation:ore>,
    <thermalfoundation:ore:1>,
    <thermalfoundation:ore:2>,
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:uncontrolled"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:dropper"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:vertical"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:splitter"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:extract"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:covered"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:droppercovered"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:verticalcovered"}),
    <immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:extractcovered"}),
    <immersiveengineering:skyhook>,
    <immersiveengineering:bullet:2>.withTag({bullet: "flare"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "potion"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "dragonsbreath"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "silver"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "he"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "buckshot"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "armor_piercing"}),
    <immersiveengineering:bullet:2>.withTag({bullet: "casull"}),
    <immersiveengineering:bullet>,
    <immersiveengineering:mold:3>,
    <immersiveengineering:material:15>,
    <immersiveengineering:material:16>,
    <immersiveengineering:material:14>,
    <immersiveengineering:material:13>,
    <immersiveengineering:metal_ladder>,
    <immersiveengineering:revolver>,
    <immersiveengineering:speedloader>,
    <immersiveengineering:mold:6>,
    <immersiveengineering:mold:7>,
    <immersiveengineering:metal_device1:11>,
    <immersiveengineering:metal_device1:10>,
    <thermalfoundation:ore:3>,
    <thermalfoundation:ore:5>,
    <thermalfoundation:ore:6>,
    <thermalfoundation:ore:7>,
    <immersiveengineering:metal:21>,
    <thermalfoundation:material:68>,
    <immersiveengineering:metal:10>,
    <galacticraftcore:ic2compat>,
    <enderio:item_endergy_conduit:2>,
    <srparasites:infestremain>,
    <mekanism:dust>,
    <galacticraftcore:oxygen_concentrator>,
    <galacticraftcore:parachute>,
    <galacticraftcore:refinery>,
    <galacticraftcore:fuel_loader>,
    <galacticraftcore:distributor>,
    <galacticraftcore:collector>,
    <galacticraftcore:oxygen_compressor>,
    <galacticraftcore:oxygen_compressor:4>,
    <galacticraftcore:sealer>,
    <galacticraftcore:oxygen_detector>,
    <galacticraftcore:machine2:8>,
    <galacticraftcore:oxygen_mask>,
    <galacticraftcore:oxygen_gear>,
    <galacticraftcore:oxygen_tank_light_full>,
    <galacticraftcore:oxygen_tank_light_full:900>,
    <galacticraftcore:oxygen_tank_med_full>,
    <galacticraftcore:oxygen_tank_med_full:1800>,
    <galacticraftcore:oxygen_tank_heavy_full>,
    <galacticraftcore:oxygen_tank_heavy_full:2700>,
    <galacticraftcore:air_vent>,
    <galacticraftcore:air_fan>,
    <galacticraftplanets:canister_partial_lox:1>,
    <galacticraftcore:bucket_fuel>,
    <galacticraftcore:fuel_canister_partial:1>,
    <galacticraftcore:machine:12>,
    <galacticraftcore:machine2>,
    <galacticraftcore:machine4>,
    <galacticraftplanets:thermal_padding>,
    <galacticraftplanets:thermal_padding:1>,
    <galacticraftplanets:thermal_padding:2>,
    <galacticraftplanets:item_basic_asteroids:6>,
    <galacticraftplanets:thermal_padding:3>,
    <galacticraftcore:standard_wrench>,
    <galacticraftcore:basic_item:19>,
    <galacticraftcore:rocket_workbench>,
    <mysticalmechanics:gear_iron>,
    <enderio:item_endergy_conduit:1>,
    <appliedenergistics2:material:40>,
    <trinity:light_container>,
    <trinity:medium_container>,
    <trinity:heavy_container>,
    <immersiveengineering:storage:1>,
    <galacticraftcore:basic_block_core:11>,
    <enderio:item_material:9>,
    <thermalfoundation:storage:7>,
    <thermalfoundation:material:327>,
    <thermalfoundation:material:199>,
    <thermalfoundation:material:135>,
    <thermalfoundation:material:71>,
    <qmd:ingot:9>,
    <immersiveengineering:material:20>,
    <mekanism:dust:3>,
    <nuclearcraft:dust>,
    <enderio:item_endergy_conduit:4>,
    <srparasites:srpweb>,
    <srparasites:itemtab>,
    <srparasites:itemthrow>,
    <randomthings:ingredient>,
    <nuclearcraft:boots_boron_nitride>,
    <nuclearcraft:legs_boron_nitride>,
    <randomthings:bottleofair>,
    <randomthings:imbue:3>,
    <randomthings:imbue:2>,
    <randomthings:imbue:1>,
    <randomthings:imbue>,
    <randomthings:magichood>,
    <randomthings:beanstew>,
    <randomthings:beans:2>,
    <randomthings:beans:1>,
    <randomthings:beans>,
    <randomthings:summoningpendulum>,
    <randomthings:biomecrystal>,
    <randomthings:spectreenergyinjector>,
    <planetprogression:telescope_fake_block>,
    <planetprogression:block_multi>,
    <planetprogression:advanced_launch_pad_full>,
    <openblocks:sonic_glasses>,
    <nuclearcraft:chest_boron_nitride>,
    <nuclearcraft:helm_boron_nitride>,
    <nuclearcraft:spaxelhoe_boron_nitride>,
    <nuclearcraft:hoe_boron_nitride>,
    <nuclearcraft:axe_boron_nitride>,
    <nuclearcraft:shovel_boron_nitride>,
    <nuclearcraft:pickaxe_boron_nitride>,
    <randomthings:enderletter>,
    <randomthings:rezstone>,
    <nuclearcraft:sword_boron_nitride>,
    <nuclearcraft:sword_boron>,
    <nuclearcraft:pickaxe_boron>,
    <nuclearcraft:shovel_boron>,
    <nuclearcraft:axe_boron>,
    <nuclearcraft:hoe_boron>,
    <nuclearcraft:spaxelhoe_boron>,
    <nuclearcraft:helm_boron>,
    <nuclearcraft:chest_boron>,
    <nuclearcraft:legs_boron>,
    <nuclearcraft:boots_boron>,
    <mekanismtools:glowstonepickaxe>,
    <mekanismtools:glowstoneaxe>,
    <mekanismtools:glowstoneshovel>,
    <mekanismtools:glowstonehoe>,
    <mekanismtools:glowstonesword>,
    <mekanismtools:glowstonepaxel>,
    <mekanismtools:glowstonehelmet>,
    <mekanismtools:glowstonechestplate>,
    <mekanismtools:glowstoneleggings>,
    <mekanismtools:glowstoneboots>,
    <mekanismtools:osmiumpickaxe>,
    <mekanismtools:osmiumshovel>,
    <mekanismtools:osmiumaxe>,
    <mekanismtools:osmiumhoe>,
    <mekanismtools:osmiumsword>,
    <mekanismtools:osmiumpaxel>,
    <mekanismtools:osmiumhelmet>,
    <mekanismtools:osmiumchestplate>,
    <mekanismtools:osmiumleggings>,
    <mekanismtools:osmiumboots>,
    <mekanismtools:lapislazulipickaxe>,
    <mekanismtools:lapislazuliaxe>,
    <mekanismtools:lapislazulishovel>,
    <mekanismtools:lapislazulisword>,
    <mekanismtools:lapislazulipaxel>,
    <mekanismtools:lapislazulihelmet>,
    <mekanismtools:lapislazulichestplate>,
    <mekanismtools:lapislazulileggings>,
    <mekanismtools:lapislazuliboots>,
    <mekanismtools:obsidianboots>,
    <mekanismtools:obsidianleggings>,
    <mekanismtools:obsidianchestplate>,
    <mekanismtools:obsidianhelmet>,
    <mekanismtools:obsidianpaxel>,
    <mekanismtools:obsidiansword>,
    <mekanismtools:obsidianhoe>,
    <mekanismtools:obsidianshovel>,
    <mekanismtools:obsidianaxe>,
    <mekanismtools:obsidianpickaxe>,
    <mekanismtools:stonepaxel>,
    <mekanismtools:woodpaxel>,
    <industrialupgrade:ruby_helmet>,
    <industrialupgrade:ruby_chestplate>,
    <industrialupgrade:ruby_leggings>,
    <industrialupgrade:ruby_boots>,
    <industrialupgrade:topaz_helmet>,
    <industrialupgrade:topaz_chestplate>,
    <industrialupgrade:topaz_leggings>,
    <industrialupgrade:topaz_boots>,
    <industrialupgrade:sapphire_helmet>,
    <industrialupgrade:sapphire_chestplate>,
    <industrialupgrade:sapphire_leggings>,
    <industrialupgrade:sapphire_boots>,
    <industrialupgrade:iu_bags>.withTag({charge: 50000.0}),
    <industrialupgrade:iu_bags:27>,
    <industrialupgrade:adv_iu_bags>.withTag({charge: 75000.0}),
    <industrialupgrade:adv_iu_bags:27>,
    <industrialupgrade:imp_iu_bags>.withTag({charge: 100000.0}),
    <industrialupgrade:imp_iu_bags:27>,
    <ic2:crafting:38>,
    <ic2:te:88>,
    <galacticraftcore:magnetic_table>,
    <ic2:forge_hammer>,
    <ic2:cutter>,
    <mutantbeasts:hulk_hammer>,
    <tconstruct:wood_rail_trapdoor>,
    <tconstruct:wood_rail>,
    <tconstruct:piggybackpack>,
    <randomthings:emeraldcompass>,
    <randomthings:superlubricentboots>,
	<qmd:sword_tungsten_carbide>,
	<qmd:pickaxe_tungsten_carbide>,
	<qmd:shovel_tungsten_carbide>,
	<qmd:axe_tungsten_carbide>,
	<qmd:hoe_tungsten_carbide>,
	<thermalexpansion:augment:576>,
	<appliedenergistics2:certus_quartz_axe>,
	<appliedenergistics2:certus_quartz_hoe>,
	<appliedenergistics2:certus_quartz_spade>,
	<appliedenergistics2:certus_quartz_pickaxe>,
	<appliedenergistics2:certus_quartz_sword>,
	<appliedenergistics2:nether_quartz_axe>,
	<appliedenergistics2:nether_quartz_hoe>,
	<appliedenergistics2:nether_quartz_spade>,
	<appliedenergistics2:nether_quartz_pickaxe>,
	<appliedenergistics2:nether_quartz_sword>,
	<draconicevolution:generator>,
	<enderio:block_decoration2:10>,
	<draconicevolution:generator>,
	<galacticraftcore:machine>,
	<mekanismgenerators:generator>,
	<industrialupgrade:basemachine2:4>,
	<ic2:te:17>,
	<industrialupgrade:basemachine2:5>,
	<notreepunching:mattock/diamond>,
	<notreepunching:saw/iron>,
	<notreepunching:saw/gold>,
	<notreepunching:saw/diamond>,
	<notreepunching:knife/iron>,
	<notreepunching:knife/gold>,
	<notreepunching:knife/diamond>,
	<notreepunching:mattock/iron>,
	<notreepunching:mattock/gold>,
	<draconicevolution:generator>,
	<galacticraftcore:machine>,
	<mekanismgenerators:generator>,
	<industrialupgrade:basemachine2:4>,
	<ic2:te:3>,
	<industrialupgrade:basemachine2:5>,
	<enderio:block_stirling_generator>,
	<randomthings:dungeonchestgenerator>,
	<notreepunching:ceramic_small_vessel>,
	<notreepunching:pottery/flower_pot>,
	<notreepunching:ceramic_large_vessel>,
	<notreepunching:pottery/large_vessel>,
	<notreepunching:rock/stone>,
	<notreepunching:rock/andesite>,
	<notreepunching:rock/granite>,
	<notreepunching:rock/diorite>,
	<notreepunching:rock/sandstone>,
	<notreepunching:rock/red_sandstone>,
	<notreepunching:rock/marble>,
	<notreepunching:rock/limestone>,
	<notreepunching:rock/basalt>,
	<notreepunching:hoe/flint>,
	<notreepunching:cobblestone/basalt>,
	<nuclearcraft:portable_ender_chest>,
	//Bronze stuff
	<mekanismtools:bronzepickaxe>,
	<mekanismtools:bronzeaxe>,
	<mekanismtools:bronzeshovel>,
	<mekanismtools:bronzehoe>,
	<mekanismtools:bronzesword>,
	<mekanismtools:bronzepaxel>,
	<mekanismtools:bronzehelmet>,
	<mekanismtools:bronzechestplate>,
	<mekanismtools:bronzeleggings>,
	<mekanismtools:bronzeboots>,
	<ic2:bronze_boots>,
	<ic2:bronze_chestplate>,
	<ic2:bronze_helmet>,
	<ic2:bronze_leggings>,
	<ic2:bronze_axe>,
	<ic2:bronze_hoe>,
	<ic2:bronze_pickaxe>,
	<ic2:bronze_shovel>,
	<ic2:bronze_sword>,
	<thermalfoundation:coin:99>,
	//steel
	<mekanismtools:steelboots>,
	<mekanismtools:steelleggings>,
	<mekanismtools:steelchestplate>,
	<mekanismtools:steelhelmet>,
	<mekanismtools:steelpaxel>,
	<mekanismtools:steelsword>,
	<mekanismtools:steelhoe>,
	<mekanismtools:steelshovel>,
	<mekanismtools:steelaxe>,
	<mekanismtools:steelpickaxe>,
	<immersiveengineering:sword_steel>,
	<immersiveengineering:hoe_steel>,
	<immersiveengineering:axe_steel>,
	<immersiveengineering:shovel_steel>,
	<immersiveengineering:pickaxe_steel>,

	//ducts & pipes
	<thermaldynamics:duct_0>,
	<thermaldynamics:duct_0:1>,
	<thermaldynamics:duct_16>,
	<thermaldynamics:duct_16:1>,
	<thermaldynamics:duct_16:5>,
	<galacticraftcore:aluminum_wire:3>,
	<galacticraftcore:aluminum_wire:2>,
	<galacticraftcore:aluminum_wire:1>,
	<galacticraftcore:aluminum_wire>,
	<galacticraftcore:enclosed:15>,
	<galacticraftcore:enclosed:1>,
	<galacticraftcore:enclosed:2>,
	<galacticraftcore:enclosed:3>,
	<galacticraftcore:enclosed:14>,
	<galacticraftcore:enclosed:5>,
	<galacticraftcore:enclosed:6>,
	<galacticraftcore:enclosed:13>,

	<galacticraftcore:steel_boots>,
	<galacticraftcore:steel_chestplate>,
	<galacticraftcore:steel_leggings>,
	<galacticraftcore:steel_helmet>,
	<galacticraftcore:steel_sword>,
	<galacticraftcore:steel_shovel>,
	<galacticraftcore:steel_hoe>,
	<galacticraftcore:steel_axe>,
	<galacticraftcore:steel_pickaxe>,
	<galacticraftplanets:desh_pick>,
	<galacticraftplanets:desh_pick_slime>,
	<galacticraftplanets:desh_axe>,
	<galacticraftplanets:desh_hoe>,
	<galacticraftplanets:desh_spade>,
	<galacticraftplanets:desh_sword>,
	<galacticraftplanets:desh_helmet>,
	<galacticraftplanets:desh_chestplate>,
	<galacticraftplanets:desh_leggings>,
	<galacticraftplanets:desh_boots>,
	<ic2:pipe>.withTag({size: 0 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 1 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 2 as byte, type: 0 as byte}),
	<ic2:pipe>.withTag({size: 3 as byte, type: 0 as byte}),
	<industrialupgrade:iridium>.withTag({advDmg: 0}),
	<industrialupgrade:compressiridium>.withTag({advDmg: 0}),
	<industrialupgrade:spectral>.withTag({advDmg: 0}),
	<industrialupgrade:myphical>.withTag({advDmg: 0}),
	<industrialupgrade:neutron>.withTag({advDmg: 0}),
	<industrialupgrade:photon>.withTag({advDmg: 0}),
	<industrialupgrade:barionrotor>.withTag({advDmg: 0}),
	<industrialupgrade:adronrotor>.withTag({advDmg: 0}),
	<industrialupgrade:ultramarinerotor>.withTag({advDmg: 0}),
    <randomthings:diviningrod>,
    <randomthings:diviningrod:1>,
    <randomthings:diviningrod:2>,
    <randomthings:diviningrod:3>,
    <randomthings:diviningrod:5>,
    <randomthings:diviningrod:4>,
    <randomthings:diviningrod:6>,
    <randomthings:diviningrod:8>,
    <randomthings:diviningrod:9>,
    <randomthings:diviningrod:10>,
    <randomthings:diviningrod:11>,
    <randomthings:diviningrod:12>,
    <randomthings:diviningrod:13>,
    <randomthings:diviningrod:14>,
    <randomthings:diviningrod:15>,
    <randomthings:diviningrod:16>,
    <randomthings:diviningrod:17>,
    <randomthings:diviningrod:18>,
    <randomthings:diviningrod:19>,
    <randomthings:diviningrod:21>,
	<randomthings:eclipsedclock>,
	<randomthings:spectreilluminator>,
	<randomthings:floopouch>,
	<randomthings:grassseeds:*>,
	<randomthings:spectrekey>,
	<randomthings:spectreanchor>,
	<randomthings:spectresword>,
	<randomthings:spectrepickaxe>,
	<randomthings:spectreaxe>,
	<randomthings:spectreshovel>,
	<randomthings:runedust:*>,
	<randomthings:spectrecharger>,
	<randomthings:spectrecharger:1>,
	<randomthings:spectrecharger:2>,
	<randomthings:spectrecharger:3>,
	<randomthings:sakanade>,
	<randomthings:floobrick>,
	<randomthings:spectrecore>,
	<ftbquests:loot_crate_storage>,
	<ftbquests:loot_crate_opener>,
	<lootbags:loot_recycler>,
	<ironchest:iron_shulker_box_white:5>,
	<ironchest:iron_shulker_box_orange:5>,
	<ironchest:iron_chest:5>,
	<ironchest:diamond_crystal_shulker_upgrade>,
	<ironchest:iron_shulker_box_light_blue:5>,
	<ironchest:iron_shulker_box_lime:5>,
	<ironchest:iron_shulker_box_magenta:5>,
	<ironchest:iron_shulker_box_yellow:5>,
	<ironchest:iron_shulker_box_pink:5>,
	<ironchest:iron_shulker_box_silver:5>,
	<ironchest:iron_shulker_box_black:5>,
	<ironchest:iron_shulker_box_red:5>,
	<ironchest:iron_shulker_box_brown:5>,
	<industrialforegoing:conveyor:*>,
	<industrialforegoing:conveyor_upgrade:*>,
	<randomthings:endermailbox>,
	<randomthings:pitcherplant>,
	<randomthings:blockbreaker>,
	<randomthings:blockdestabilizer>,
	<randomthings:ancientbrick>,
	<randomthings:soundbox>,
	<randomthings:sounddampener>,
	<randomthings:enderbridge>,
	<randomthings:prismarineenderbridge>,
	<randomthings:enderanchor>,
	<randomthings:beanpod>,
	<randomthings:specialchest>,
	<randomthings:specialchest:1>,
	<randomthings:customworkbench>.withTag({woodName: "minecraft:planks", woodMeta: 5}),
	<randomthings:customworkbench>.withTag({woodName: "minecraft:planks", woodMeta: 4}),
	<randomthings:customworkbench>.withTag({woodName: "minecraft:planks", woodMeta: 3}),
	<randomthings:customworkbench>.withTag({woodName: "minecraft:planks", woodMeta: 2}),
	<randomthings:customworkbench>.withTag({woodName: "minecraft:planks", woodMeta: 1}),
	<randomthings:customworkbench>.withTag({woodName: "minecraft:planks", woodMeta: 0}),
	<ic2:te:100>,
	<ic2:te:101>,
	<ic2:te:102>,
	<ncsteamadditions:copper_wire>
]);

removeAndHideAndFurnaceItems([
	//ingots
	<immersiveengineering:metal:5>,
	<nuclearcraft:ingot:4>,

	<galacticraftcore:basic_item:3>,
	<immersiveengineering:metal>,
	<mekanism:ingot:5>,
	<nuclearcraft:ingot>,
	<thermalfoundation:material:128>,

	<thermalfoundation:material:131>,
	<nuclearcraft:ingot:2>,
	<immersiveengineering:metal:2>,
	<galacticraftplanets:basic_item_venus:1>,

	<thermalfoundation:material:129>,
	<nuclearcraft:ingot:1>,
	<mekanism:ingot:6>,
	<galacticraftcore:basic_item:4>,

	<thermalfoundation:material:134>,
	<qmd:ingot:10>,

	<nuclearcraft:ingot:3>,

	<qmd:ingot:5>,
	<thermalfoundation:material:133>,
	<immersiveengineering:metal:4>,

	<immersiveengineering:metal:3>,
	<thermalfoundation:material:130>,

	<nuclearcraft:ingot:7>,

	<immersiveengineering:metal:8>,
	<mekanism:ingot:4>,
	<nuclearcraft:alloy:5>,
	<thermalfoundation:material:160>,

	<mekanism:ingot:2>,
	<nuclearcraft:alloy>,
	<thermalfoundation:material:163>,

	<thermalfoundation:material:162>,

	<immersiveengineering:metal:7>,
	<thermalfoundation:material:161>,
	<thermalfoundation:material:164>,
	<thermalfoundation:material:228>

	<thermalfoundation:material:33>,
    <immersiveengineering:metal:40>,
    <enderio:item_material:25>,
    <appliedenergistics2:material:51>,
    <immersiveengineering:metal:19>,
    <mekanism:dust:1>,
    <thermalfoundation:material:1>,
    <qmd:dust:7>,
    <immersiveengineering:material:25>,
    <immersiveengineering:metal:33>,
    <thermalfoundation:material:322>,
    <nuclearcraft:dust:13>,
    <nuclearcraft:gem_dust:6>,
    <thermalfoundation:material:771>,
    <mekanism:otherdust:3>,
    <mekanism:sawdust>,
    <enderio:item_material:23>,
    <nuclearcraft:gem_dust:7>,
    <thermalfoundation:material:768>,
    <nuclearcraft:gem_dust:3>,
    <mekanism:otherdust:6>,
    <thermalfoundation:material:770>,
    <enderio:item_material:29>,
    <enderio:item_material:32>,
    <mekanism:otherdust>,
    <nuclearcraft:gem_dust>,
    <industrialupgrade:itemingots:14>,
    <nuclearcraft:ingot:13>,
    <nuclearcraft:ingot:11>,
    <tconstruct:ingots>,
    <qmd:ingot:4>,
    <qmd:ingot:8>,
    <qmd:ingot>,
    <qmd:ingot:2>,
    <galacticraftplanets:item_basic_asteroids>,
    <qmd:ingot:3>
]);


removeRecipes([
    <minecraft:flint_and_steel>,
    <randomthings:diviningrod:7>,
    <mekanismgenerators:turbineblade>,
    <immersiveengineering:stone_decoration>,
    <ic2:cable:4>.withTag({type: 4 as byte, insulation: 0 as byte}),
    <ic2:cable>.withTag({type: 0 as byte, insulation: 0 as byte}),
    <ic2:plate:1>,
    <ic2:plate:2>,
    <ic2:plate:3>,
    <ic2:plate:5>,
    <ic2:plate:8>,
    <ic2:casing:6>,
    <ic2:casing:1>,
    <ic2:casing:4>,
    <ic2:casing:3>,
    <ic2:casing:2>,
    <industrialupgrade:moremachine2>,
    <industrialupgrade:moremachine2:4>,
    <ic2:plate:1>,
    <ic2:plate:2>,
    <ic2:plate:3>,
    <ic2:plate:5>,
    <ic2:plate:8>,
    <ic2:plate:8>,
    <ic2:casing:1>,
    <ic2:casing:2>,
    <ic2:casing:3>,
    <ic2:casing:6>,
    <ic2:casing:4>,
    <ic2:casing:6>,
    <minecraft:furnace>,
    <galacticraftcore:machine2>,
    <galacticraftcore:machine4>,
    <galacticraftcore:solar>,
    <galacticraftcore:machine2:4>,
    <galacticraftcore:machine2:12>,
    <galacticraftcore:basic_item:1>,
    <galacticraftcore:basic_item>,
    <galacticraftplanets:mars_machine:8>,
    <galacticraftplanets:geothermal_generator>,
    <planetprogression:satellite_launcher>,
    <galacticraftplanets:basic_item_venus:5>
]);

